### ISSUE TITLE
Please clarify the data format cal-heatmap is expecting!

### ISSUE THREAD

**Issue by aionescu-zz** [wa0x6e/cal-heatmap#1]
Could you please clarify the data format that cal-heatmap is expecting?

If I download your JSON, that seems to work, but if I generate timestamps with values, they don't seems to be rendered, but also no error messages seems to appear in the console:
![cal-heatmpa-not_rendering](https://f.cloud.github.com/assets/339635/278761/79fba680-90f3-11e2-8b73-694e2a4d17a1.png)

My HTML file: https://gist.github.com/aionescu/10a1be90f135ccabc867
My JSON file: https://gist.github.com/aionescu/3ea6a5d7849b14569037

I just included cal-heatmap using Bower: `bower install cal-heatmap`, so it fetched automatically the required dependencies(d3), so that's why they're in the "components" directory.

**Comment by mmunchandersen** [comment]
my 5 cents: http://stackoverflow.com/questions/29860376/why-does-my-cal-heatmap-not-not-display-data
