### ISSUE TITLE
Additional Data in the Tooltip

### ISSUE THREAD

**Issue by koalaboy808** [wa0x6e/cal-heatmap#102]
My calendar only takes in four values (0,1,2,3). The four values correspond to days in my local school calendar year (0 - Regular Days, 1 - Holidays, 2 - Teacher Days, 3 - School Meeting) I would like the tooltip to label them more discretely (i.e. the type of Holiday or the type of School Meeting). I've looked through 'subDomainTitleFormat' but can't seem to find a solution. Is it possible to represent data other than date and value? 

Hopefully I'm being clear enough. Here are a few examples though of my ideal tooltip:
- Christmas, December 25, 2015
- New Teacher Orientation, May 26, 2015

Thanks!

**Comment by devcollectief** [comment]
I created a pull request that allows for this functionality #169

**Comment by Yurko-Fedoriv** [comment]
You can.
subDomainTitleFormat expects a string with placeholders which is then executed against overloaded String.propotype.format().
If you hack this and pass ```subDomainTitleFormat: {format: function(params){}}``` you can do whatever you want in the custom function.

**Comment by rizwanshah29** [comment]
How can I get data in my tool tip?

**Comment by rizwanshah29** [comment]
How it's possible that we can get studentdata in tool tip?
When I will be hover on my subdomain date.

**Comment by wa0x6e** [comment]
For now, you can't, it's WIP

**Comment by manojkumar82** [comment]
is there an update on customizing tool tip as we want to add some information apart from date and value, to show in tool tip.

**Comment by wa0x6e** [comment]
#169 merge into V4 branch
