### ISSUE TITLE
no date past 08

### ISSUE THREAD

**Issue by scsi050** [wa0x6e/cal-heatmap#115]
hi, in cal-heatmap v3.4.0, (using Chrome 38.0.2125.111 and FireFox v28.0) i'm having an issue where no date past day 08 is displayed, even though i'm using the sample code for Month > hour. Is this a known issue ? (see attachment for screenshot).

![error](https://cloud.githubusercontent.com/assets/9487453/4867274/737ac2a2-6133-11e4-9eb3-4b250d775110.gif)

var calendar = new CalHeatMap();
calendar.init({
        data: "datas-years.json",
        start: new Date(2000, 0),
        id : "graph_f",
        domain : "month",
        subDomain : "hour",
        range : 1,
        cellsize: 6,
        cellpadding: 1
});

**Comment by kamisama** [comment]
I just checked, and the month domain + hour subdomain is not supported.

Are you sure you want/need to display a heatmap of 800 nodes ?

**Comment by wa0x6e** [comment]
Fixed in v4
