### ISSUE TITLE
jumpTo method doesn't trigger events?

### ISSUE THREAD

**Issue by fnoop** [wa0x6e/cal-heatmap#121]
Hi

I'm drawing multiple heatmaps on a screen which works fine.  I have the data set to a URL with {{t:start}} and {{t:end}} so whenever I call jumpTo on a heatmap it goes and fetches the new data and then repaints the heatmap with the new data.  I set onComplete() and onClick() with functions that adds modal triggers and a few other things so when a date cell is clicked a modal pops up and calls ajax content. This is all cool and works most awesomely, the problem is that after calling the new data through jumpTo and repainting the heatmap, it doesn't seem to trigger onComplete() event so the new date cells are 'dead' - I've no way of adding the triggers back.

Is there a way of forcing the onComplete trigger after an update, even if it means hacking the source a bit?

**Comment by kamisama** [comment]
You can use the `afterLoadNextDomain` and `afterLoadPreviousDomain` callbacks to trigger your events after a `JumpTo()`.
