### ISSUE TITLE
Support displaying arbitrary time zone settings.

### ISSUE THREAD

**Issue by jblz** [wa0x6e/cal-heatmap#122]
It appears that the visualization displays data points based on the client browser's timezone offset and I can't seem to change it.

I can hack my data object by adding `(new Date( timestamp * 1000 )).getTimezoneOffset() * 60` to each of the keys to make it display in UTC (desirable in my application).

Here's an example which illustrates this:
http://codepen.io/jblz/pen/XJdLwx

It would be nice to be able to supply an offset to override the client when the data being visualized are in a different time zone.

**Comment by nimaen** [comment]
Up ? It's been a year now, have you been able to have a look at it ?

**Comment by svbeon** [comment]
I'd like to +1 this as well, though I'm thinking maybe we should provide an `afterLoadData` snippet in the meantime.

I'll give it a go

**Comment by BigChief45** [comment]
@wa0x6e any updates on this?

I am experiencing an issue that is possibly related. Timestamps are stored with the correct dates, but Cal Heatmap highlights the wrong date (highlights the previous day):

Timestamp (human time):

```
Saturday, August 5, 2017 12:00:00 AM
```

![image](https://user-images.githubusercontent.com/6859247/29005851-c7b304e4-7aa1-11e7-8fe1-f47e32c24dd8.png)

**Comment by wa0x6e** [comment]
indeed, the calendar is always using the browsers' timezone. Customizing the timezone is in the todo list.

**Comment by BigChief45** [comment]
@wa0x6e Thanks for the response. Any idea on when this could occur?

**Comment by AdamWill** [comment]
Just figured out that this is probably why [Pagure](https://pagure.io) user activity heatmaps are frequently off by a day for users in timezones a long way from UTC.

**Comment by BigChief45** [comment]
@wa0x6e Any updates on this?

**Comment by alanmels** [comment]
Also need this feature.

**Comment by wa0x6e** [comment]
Added in v4
