### ISSUE TITLE
tooltip contained by {overflow:hidden / auto} not fully displayed

### ISSUE THREAD

**Issue by harlanlewis** [wa0x6e/cal-heatmap#131]
I am displaying a calendar heatmap inside a sidebar with `{overflow: auto}` for vertical scrolling. Because the tooltip is also contained by the sidebar, it is cut off at the edges (screenshot attached).

A frequent practice for tooltips is to insert them at the end of `body`, with more JS for finding and maintaining their position as the user scrolls or elements move around. Are there any plans for this? Would this be a welcome pull request?

![monosnap 2015-01-30 10-46-58](https://cloud.githubusercontent.com/assets/51766/5981318/f59b23cc-a86d-11e4-9474-9e92f95697b6.png)

**Comment by harlanlewis** [comment]
Note I have resolved this issue in my project by using Tipsy (http://onehackoranother.com/projects/jquery/tipsy/) instead of Cal Heatmap's tooltips.

**Comment by ChiaYuSu** [comment]
> Note I have resolved this issue in my project by using Tipsy (http://onehackoranother.com/projects/jquery/tipsy/) instead of Cal Heatmap's tooltips.

I would like to ask you how you replaced the CalHeatMap tooltip to Tipsy tooltip

**Comment by wa0x6e** [comment]
Fixed in v4, now using popperjs

**Comment by ChiaYuSu** [comment]
> Fixed in v4, now using popperjs

Is there any newset version of cdn.js, thank you

**Comment by wa0x6e** [comment]
Not yet, build is till in beta
