### ISSUE TITLE
Weird empty cell

### ISSUE THREAD

**Issue by infacq** [wa0x6e/cal-heatmap#133]
![untitled](https://cloud.githubusercontent.com/assets/1596891/6077802/87b2cc82-ae2d-11e4-96d8-f23d847a8a94.png)

see year `2012`, there is weird empty cell between cell 17 and 26

and the problems always happen at the end of the year. (see the first domain at the most left)

![untitled](https://cloud.githubusercontent.com/assets/1596891/6077909/b5f10748-ae2e-11e4-8e7b-06d093d5a08f.png)

**Comment by kamisama** [comment]
What's the used domain and subDomain ?

**Comment by infacq** [comment]
domain is year and subdomain was week

**Comment by infacq** [comment]
hi is this still a bug

**Comment by kamisama** [comment]
What does the number inside the cells represent ? The value ? Or a date ?

**Comment by infacq** [comment]
value of integet

**Comment by vnen** [comment]
I have the same problem (missing October 19):

![Missing cell](https://cloud.githubusercontent.com/assets/5599796/6630766/73dbebec-c8fb-11e4-9a31-0482099ccb50.png)

**Comment by wa0x6e** [comment]
Related to #87, fixed in v4

The cell before the empty cell is the last week of the year, and the cell after is the first week of the year. It's a positioning issue, since the week number is like 53, but week 53 of the previous year
