### ISSUE TITLE
nodejs?

### ISSUE THREAD

**Issue by hampsterx** [wa0x6e/cal-heatmap#139]
is there anything stopping this from working on the server side?
Haven't tried yet :)

**Comment by kamisama** [comment]
How will you use it on NodeJS ?

The graph is only useful when rendered inside a webpage.

**Comment by hampsterx** [comment]
a couple of cases for server side rendering to svg/png

- inclusion in reports (pdf)
- inclusion in other online documentation (markdown readme file is my use case)

Happy to have an initial hack if you can suggest a starting vector

**Comment by kamisama** [comment]
I'm afraid I'm not familiar enough with nodejs to help you with this.

**Comment by vnen** [comment]
@hampsterx the major problem is that the heatmap need a selector (an actual element) to be inserted. It might work if you use [jsdom](https://github.com/tmpvar/jsdom) to create a virtual DOM in the server. [This guide](http://mango-is.com/blog/engineering/pre-render-d3-js-charts-at-server-side.html) might help.

**Comment by nyquist212** [comment]
Have you seen this? http://mango-is.com/blog/engineering/pre-render-d3-js-charts-at-server-side.html

**Comment by wa0x6e** [comment]
Should works fine since v4, as all jest tests are now using JSDOM and node
