### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by bobrabih** [wa0x6e/cal-heatmap#144]
First of all, I would like to thank you for your great work .
I want to render this calendar from right to left .
Any help plz ..

**Comment by devo5teee** [comment]
+1

**Comment by kamisama** [comment]
You're talking about RTL, as in arabic RTL, or just reverse the presentation order of the domain, and keeping the subdomain order ?

**Comment by bobrabih** [comment]
yes arabic RTL
