### ISSUE TITLE
Specify number-format for subDomainTitleFormat

### ISSUE THREAD

**Issue by k-nut** [wa0x6e/cal-heatmap#146]
You provide the `subDomainDateFormat` that lets the users format the date according to their needs. It would be nice to have a `subDomainCountFormat` so that the values can be formated as well (e.g. German uses a `.` as 1000-delimiter and `,` as fraction delimiter as in `10.000,20`).
If you agree that this would be useful I can send in a small pull request. Just wanted to make sure that this functionality does not already exist and I only missed it in the docs.

**Comment by kamisama** [comment]
What values that option would be formatting ? The values inside the cells, or the values in the title ? 

It would be interesting to allow more formatting options, such as the decimal mark too.

**Comment by kamisama** [comment]
Take a look at https://github.com/mbostock/d3/wiki/Formatting, it may help

**Comment by wa0x6e** [comment]
Added in v4
