### ISSUE TITLE
Show only weekdays

### ISSUE THREAD

**Issue by jasonirwin** [wa0x6e/cal-heatmap#151]
Is it possible to hide weekends and effectively only show weekdays (domain: month, subDomain: x_Day)? If not, would you accept a pull request for something along the lines of a x_Weekday subDomain?

**Comment by kamisama** [comment]
It is not possible in the current version. But you could always display them in another special color.

weekday subdomain makes sense, you could try it.

**Comment by jacobSpitzer** [comment]
how can i display a special color on certain weekdays without specifying a data list from dates?

**Comment by wa0x6e** [comment]
See #164
