### ISSUE TITLE
Possible to display additional info on cell hover?

### ISSUE THREAD

**Issue by Yorgg** [wa0x6e/cal-heatmap#152]
I am building a daily task manager - could I use cal-heatmap to display the daily tasks when the cell is hovered?  So on a mouse hover (for each cell) it would display that day's results: 

2 out of 2 tasks completed on 2014, January 24. 
1. Take out garbage
2. Mow the lawn

Thanks.

**Comment by kamisama** [comment]
It's not possible right now, as cal-heatmap does not store your todo list informations. It can by adding a callback on cell hover. Coming later

**Comment by anand-patel** [comment]
+1

**Comment by GPSMAGIC** [comment]
Any news ?

**Comment by wa0x6e** [comment]
Closing, see #102

**Comment by lgt** [comment]
Is there any example how to hack `subDomainTitleFormat`?
