### ISSUE TITLE
Custom subDomain for 'day' as a Domain

### ISSUE THREAD

**Issue by cherrylipstick** [wa0x6e/cal-heatmap#155]
I want 'day' as domain, but I don't want 'hour' as subdomain, I want the subdomain to be my own data, is it possible?
In the example attached I need family members to be the 'subdomain'...

![screen shot 2015-06-26 at 17 09 56](https://cloud.githubusercontent.com/assets/5595322/8386473/07fb9380-1c27-11e5-8b74-df890231e208.png)

**Comment by kamisama** [comment]
No, cal-heatmap is focused on the "calendar" concept
