### ISSUE TITLE
Dynamically changing properties set during init()

### ISSUE THREAD

**Issue by kevinhooke** [wa0x6e/cal-heatmap#158]
Is it possible to change any of the values when you first call init(), like domain? I'd like to display the heatmap initially with domain='month', but allow the user to select the domain value of say day/week/month and have the heatmap redisplay. If you call init() again it creates a new heatmap, so what is the approach to change these properties after you've called init the first time?
Thanks!

**Comment by kamisama** [comment]
Currently, recreating the calendar is the only way.

**Comment by kevinhooke** [comment]
Ok, thanks. Any plans to include this as an enhancement in a future release?

**Comment by MadLittleMods** [comment]
:+1:

**Comment by dipo101** [comment]
@wa0x6e 
Hi, any progress on this enhancement?, I am specifically trying to change the subDomainTitleFormat property without having to call init() again. I see changing highlight is possible..

**Comment by wa0x6e** [comment]
Added in v4
