### ISSUE TITLE
Customize interval

### ISSUE THREAD

**Issue by mkcedward** [wa0x6e/cal-heatmap#164]
When using hour as domain and minute as subdomain, there will be 60 cells in every one hour. Does it able to support different interval? For example, when setting interval as 5, number of cells per hour will become 12?

Thanks.

**Comment by wa0x6e** [comment]
Full customization of domains and subdomain layout is planned for v4

**Comment by wa0x6e** [comment]
Add in v4, see section about `subDomainTemplate`

**Comment by Xen01r** [comment]
Hello,

Could you give us an example of how to use custom interval ?
I'm trying to set a 5 min interval by setting a custom template without success. Here is my code :

```
const FiveMinuteTemplate = DateHelper => {
  const COLUMNS_COUNT = 3
  const ROWS_COUNT = 4
  const ALLOWED_DOMAIN_TYPE = ["day", "hour"]

  return {
    name: "fivemin",
    allowedDomainType: ALLOWED_DOMAIN_TYPE,
    rowsCount: () => COLUMNS_COUNT,
    columnsCount: () => ROWS_COUNT,
    mapping: (startTimestamp, endTimestamp, defaultValues) =>
      // eslint-disable-next-line implicit-arrow-linebreak
      DateHelper.intervals(
        "5min",
        startTimestamp,
        DateHelper.date(endTimestamp)
      ).map((ts, index) => ({
        t: ts,
        x: Math.floor(index / COLUMNS_COUNT),
        y: index % COLUMNS_COUNT,
        ...defaultValues,
      })),
    extractUnit: ts =>
      DateHelper.date(ts)
        .startOf("5min")
        .valueOf()
  }
};

```

Thanks,

**Comment by wa0x6e** [comment]
> Hello,
> 
> Could you give us an example of how to use custom interval ? I'm trying to set a 5 min interval by setting a custom template without success. Here is my code :
> 
> ```
> const FiveMinuteTemplate = DateHelper => {
>   const COLUMNS_COUNT = 3
>   const ROWS_COUNT = 4
>   const ALLOWED_DOMAIN_TYPE = ["day", "hour"]
> 
>   return {
>     name: "fivemin",
>     allowedDomainType: ALLOWED_DOMAIN_TYPE,
>     rowsCount: () => COLUMNS_COUNT,
>     columnsCount: () => ROWS_COUNT,
>     mapping: (startTimestamp, endTimestamp, defaultValues) =>
>       // eslint-disable-next-line implicit-arrow-linebreak
>       DateHelper.intervals(
>         "5min",
>         startTimestamp,
>         DateHelper.date(endTimestamp)
>       ).map((ts, index) => ({
>         t: ts,
>         x: Math.floor(index / COLUMNS_COUNT),
>         y: index % COLUMNS_COUNT,
>         ...defaultValues,
>       })),
>     extractUnit: ts =>
>       DateHelper.date(ts)
>         .startOf("5min")
>         .valueOf()
>   }
> };
> ```
> 
> Thanks,

`5min` is not a valid interval. Instead, you have to create your own array, which will looks like [0, 5, 10, ... 55] then pass it to the `map` function

Use the `startTimestamp`, and extract the nearest timestamp for the minute 0, and you have the first value of your array.

Move by 5minutes, and you have tje second value., etc ....

At the end, it should be an array of timestamp, with each value separated by 5 minutes
