### ISSUE TITLE
Data is not loading from CSV

### ISSUE THREAD

**Issue by vshankaa** [wa0x6e/cal-heatmap#168]
My data is saved on a SharePoint which requires login, along with the "html" and other library files. It's in CSV format and it's not loading.

The calendar is drawn and the hour value is shown. However when the heatmap is generated. When I checked in console, the data is not getting loaded. In the function referenced in afterLoad (GAconverter) is throwing error for 'data.length'. 'data' is showing null. Would appreciate any help.

Data (the Google Analytics sample):
Hour,Visits
000000,0
000001,0
000002,1
000003,0
000004,3
000005,1
000006,0 

Code:

function GAconverter(data) {
var i, total, results = {};
	for(i = 0, total = data.length; i < total; i++) {
		results[+data[i].Hour * 3600 + startTimestamp] = +data[i].Visits;
	}
	return results;
}

var cal = new CalHeatMap();
	cal.init({
		itemSelector: "#cal-heatmap",
		domain: "day",
		subDomain: "hour",
		data: "analytics.csv",
		dataType: "csv",	
		start: new Date(2015, 8, 15),
		afterLoad: GAconverter,
		cellSize: 20,
		range: 5,
		itemName: "visit",
		legend: [5, 10, 15, 20, 25, 30],
		subDomainTextFormat: "%H"
	});

**Comment by wa0x6e** [comment]
In the network tab of your inspector, does the csv load ?

**Comment by vshankaa** [comment]
Magically it's working now! Unfortunately I wasn't able to figure out what the problem was.
