### ISSUE TITLE
Wrong init to undefined of d3 var

### ISSUE THREAD

**Issue by RaulTsc** [wa0x6e/cal-heatmap#170]
So, I have this chrome app which basically blocks website content by displaying other content on top of it. In that content there is also a cal-heatmap.

The issue:
I inject everything 'artificially' into the websites, so for the heatmap I need d3.js and cal-heatmap.js. I first inject d3.js, and then cal-heatmap.js. Now here's the thing, at line 6 in cal-heatmap there is ``` var d3 = typeof require === "function" ? require("d3") : window.d3; ``` --- Although require is not usually a property of the window object, in some cases it is (including Facebook and Quora), In that case, the d3 is initialized to ``` require('d3') ``` --- But ``` require('d3') ``` returns undefined in this case. With the help of @BerkeleyTrue I've come to the conclusion that probably cal-heatmap assumes I have absolute control of the website, but something like this can happen, and there are a lot of apps which override or modify website content.

Hope that was clear enough, and if not please reply. Thank you

**Comment by RaulTsc** [comment]
Also I should mention that my simple fix was to just comment that line, I think you just need to check if window.d3 already exists

**Comment by wa0x6e** [comment]
How do you inject d3js and cal-heatmap ? Are you using document.write('<script>') on the <head> ?

**Comment by RaulTsc** [comment]
https://github.com/RaulTsc/WorkflowEnforcer/blob/master/scripts/content_scripts/block.js#L38-L71

**Comment by wa0x6e** [comment]
Related to #200
