### ISSUE TITLE
Only display items with value

### ISSUE THREAD

**Issue by smartmeter** [wa0x6e/cal-heatmap#173]
I am displaying the entire year as a row, this works fine!

In the row, how can I display 

1      *only that items that value (value is not null or greater than 0)*,  show the Dates & Value  for e.g. if there only 40 days with value in a year, I only want to render those days - in the 1 row format.
2      How can I display the `item`  `Date and Value` a) as `vertical top option` above the item vertically or b) on hover option.

**Comment by wa0x6e** [comment]
1 -  You can not only display some dates, the whole calendar is always rendered, that's the point of a heatmap.

2 - I don't get what you mean

**Comment by smartmeter** [comment]
2.  Imagine a *single row* of all dates/items 20px in the year. I want to display a date of each items above the cal-map items like this http://4.bp.blogspot.com/-L15OXwCdmbE/UrBbp0l_i7I/AAAAAAAAq_8/BLgu6zOFKFU/s1600/vertical_text.png

**Comment by wa0x6e** [comment]
Seems impossible currently, it's not in the scope of heatmap
