### ISSUE TITLE
How to change rect colour

### ISSUE THREAD

**Issue by vshankaa** [wa0x6e/cal-heatmap#174]
Is it possible to change the colour of a specific rect (day or hour)? Let's say I want to fill 9-Nov-2015 with red or 4PM of a day in red, is this possible to do? Thanks.

**Comment by wa0x6e** [comment]
There is a `highlight()`. If it does not fulfill your need, you have to use css to target the domain (http://cal-heatmap.com/#domain-highlight), then use `g:nth-child()` to target your rect.

**Comment by vshankaa** [comment]
Thanks for the quick response. I'm not able to reference to elements created by the heatmap. Would you please give a live example for better understanding? Really appreciate your help. Thanks.

**Comment by wa0x6e** [comment]
Look at http://cal-heatmap.com/#domain-highlight for how to highlight domain.
Then use `g:nth-child()` to target the specified rect. You have to use `fill` and not `background-color` to style svg element.
