### ISSUE TITLE
Calendar week column descriptor

### ISSUE THREAD

**Issue by mahadi** [wa0x6e/cal-heatmap#175]
First of all, thank you for your great job!

I am drawing a calendar with year domain and day subDomain. 
Now i would like to display the CW over each column of the calendar. 
But this also requires that the domains need to have no space between the years.

I didnt find a way to realize this with the current master branch. 
Did i miss something or is this a new feature?

**Comment by wa0x6e** [comment]
It's currently impossible for the moment
