### ISSUE TITLE
Responsive view for Cal-heatmap chart

### ISSUE THREAD

**Issue by suveshJ** [wa0x6e/cal-heatmap#176]
Hi,
I'm working with Cal-heatmap chart and I'm displaying the Months i.e 3 months in a row. In normal view it is working fine for responsive view i have tried this (https://github.com/wa0x6e/cal-heatmap/issues/100) by reducing the cellSize to 20 but it is  displaying the huge gap between the rows. 

Normal View
![normalview](https://cloud.githubusercontent.com/assets/15652685/11399355/d81d6370-93ac-11e5-9d41-d041d309f209.png)
Responsive View
![responsive](https://cloud.githubusercontent.com/assets/15652685/11399414/3c6afb1c-93ad-11e5-94bd-80dbeecb488a.png)

Note: for those two images data set is different i.e range of the calender and data binded to that is different

**Comment by wa0x6e** [comment]
Can you inspect the element, and see what element is causing the gap ? Is it because there is a margin/padding in the css, or is the svg element height not resized ?

**Comment by ravish1915** [comment]
@suveshJ How to achieve above 2 rows and 3 column strucutre in calender heatmap.??

**Comment by wa0x6e** [comment]
Fixed in v4
