### ISSUE TITLE
Wrong calculation for sums

### ISSUE THREAD

**Issue by auipga** [wa0x6e/cal-heatmap#179]
in cal-heatpmap.js:2613 there is `if (!isNaN(subDomainsData[index].v)) {` but the if/else case is switched, it has to be `if (isNaN(subDomainsData[index].v)) {` without the `!`.

This bug results in values like
- `null1` (null + 1) instead of `1`
- `111` (1+1+1) instead of `3`

I'm using latest v3.3.10

**Comment by wa0x6e** [comment]
Closing, let's discuss this on #153
