### ISSUE TITLE
Non-standard encapsulation and require() use.

### ISSUE THREAD

**Issue by kbullaughey** [wa0x6e/cal-heatmap#180]
I was interested in using cal-heatmap as part of an [emberjs](http://emberjs.com/) project. However, the line that requires d3 proved a problem:

```
var d3 = typeof require === "function" ? require("d3") : window.d3;
```

In ember projects, `require` exists, but it's designed to work with its own system of modules. I'm curious if there's interest in a somewhat more standard encapsulation of cal-heatmap. I adjusted the code into what [seemed like a common format](http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/).

Have a look at [the result in my fork](https://github.com/kbullaughey/cal-heatmap/blob/fix-d3-dependency-loading/src/cal-heatmap.js).

Is there interest in moving cal-heatmap in this direction? 

One free side-effect of wrapping the whole thing in a factory method is that only one outer `"use strict";` declaration is needed.

I can confirm that this works with ember and pulling `d3` and `cal-heatmap` in as browser globals via bower, but I wasn't sure whether there are other bastard versions of `require` that the current implementation happens to work with that would be broken by my changes. 

Thoughts?

**Comment by wa0x6e** [comment]
Fixed in v4
