### ISSUE TITLE
Hiding future dates

### ISSUE THREAD

**Issue by snumb130** [wa0x6e/cal-heatmap#181]
Is there currently a way to hide subdomains that are in the future?  For example, with subdomain of `day` could days past the current day be hidden?

**Comment by wa0x6e** [comment]
You can "hide" them visually by giving them the same background color as your page

**Comment by snumb130** [comment]
Is there a way to target future days when setting color

**Comment by wa0x6e** [comment]
They have `.future` class

**Comment by snumb130** [comment]
Thanks.  Not sure how I overlooked that.  I feel a little sheepish. Closing.

**Comment by snumb130** [comment]
When looking it appears that the current date also has future.  Does this have anything to do with time settings?

**Comment by snumb130** [comment]
So what I found was the current subdomain had `.future` class.  I can add the `highlight: "now"` option and the future class goes away and `.now` is added.  This allows for the appropriate styling.

**Comment by snumb130** [comment]
It seems like the `.now` class should be on the current date no matter what and `.future` should never be on the current date.
