### ISSUE TITLE
Revisit adding an option to eliminate all whitespace between domains. 

### ISSUE THREAD

**Issue by lots0logs** [wa0x6e/cal-heatmap#184]
This was mentioned a couple years ago on #54 but I was hoping that it could be revisited. I understand there are a lot of factors involved with ensuring that nothing breaks if such an option were implemented. I also realize that the example I am about to provide is but one of countless possibilities that the plugin would see while in general use. 

With that said, take a look at the chart on [this page](http://build.antergos.com/). Maybe its a coincidence, of that I am not sure, but in that chart, it looks like everything would line up perfectly if you were to move each sub-domain item `12px` over to the left. What do you think? Is it possible?

**Comment by lots0logs** [comment]
What about allowing the user to set an offset in px (positive or negative)? Is it possible to move the elements over by a set pixel value if the user provides the value?

**Comment by wa0x6e** [comment]
It's not possible, because the whitespace is not always here. it's only
here if the month does not end on sunday/saturday, depending on use locale.

**Comment by lots0logs** [comment]
Hmm..okay I see that now. I wonder how github does it then :disappointed:

**Comment by wa0x6e** [comment]
Github does not have navigation, make everything seems easier
