### ISSUE TITLE
keep styling on q{n} selectors when value transition

### ISSUE THREAD

**Issue by leoncvlt** [wa0x6e/cal-heatmap#186]
I can give the text on cells with a value a specific style using the css selector

``` css
`.cal-heatmap-container .r1 + title + .subdomain-text`.
`.cal-heatmap-container .r2 + title + .subdomain-text`.
```

(I know the documentation says "q{n}" but it didn't work and after checking the page with the console the class is called "r{n} on the page... anyways)

Problem is that when I increase the value on that cell, the digit in the `r` class increases during the transition and goes into decimal values and thus loses the selector until it goes back to 2.

How can I use a style for all the cells associated to a specific value? I tried using css wildcards like this:

``` css
.cal-heatmap-container *[class^="r"] + title + .subdomain-text
```

but it doesn't seem to work.

**Comment by wa0x6e** [comment]
Fixed in v4
