### ISSUE TITLE
Tooltips appearing in the wrong place

### ISSUE THREAD

**Issue by robbybooker** [wa0x6e/cal-heatmap#189]
Hi!

This is a great component but I'm having trouble with the tooltips. I have 13 calendars on a page, each showing a single month and all working fine except that the tooltips for the days for ALL the calendars appear over the first calendar to be created. They appear over the correct day (roughly) in each month but over the wrong calendar (the first). The item selector for each calendar is a unique id and class combination. Does anyone have any ideas?

Rob

**Comment by wa0x6e** [comment]
Can you try adding a `position: relative` to the calendar container ?

**Comment by nyquist212** [comment]
I'm experiencing similar problems with heatmaps in Bootstrap "sections". `position:relative` didn't work for me.

**Comment by robbybooker** [comment]
Thanks. I'll try position:relative. I have however pinned the problem down to floating. I have several calendars inside the same containing div and these are all are set to float left to make the page more 'responsive'. It seems that floating left causes the tooltips for all the calendars to be associated with the first calendar that appears in the container. I need to experiment more but unfortunately I have a very long to-do list!

**Comment by wa0x6e** [comment]
Fixed in v4, now using popperjs
