### ISSUE TITLE
Two AJAX requests sent when fetching data from API?

### ISSUE THREAD

**Issue by JasperTey** [wa0x6e/cal-heatmap#190]
Whenever data is fetched from the API, two ajax requests appear to be sent (with the first one aborted/canceled). 

> **Firefox**
> 
> ![image](https://cloud.githubusercontent.com/assets/1280844/13898662/d44d8110-edae-11e5-84c0-a00b7bcdc71d.png)
> 
> **Chrome**
> 
> ![image](https://cloud.githubusercontent.com/assets/1280844/13898687/6a3db708-edaf-11e5-854d-ccef1274ae17.png)

Is this happening to anyone else? It does this consistently, on my end.

**Comment by wa0x6e** [comment]
Is it a GET or OPTION request ?

**Comment by JasperTey** [comment]
GET requests.

**Comment by wa0x6e** [comment]
Is it hosted somewhere public so I can test/reproduce ?

**Comment by maartendp** [comment]
Hey,
I have the same issue. Unfortunately, I don't have this hosted publicly but I can give you the js used.

        $('[data-type="graph"]').each(function(){
	        var el = $(this);
	        var cal = new CalHeatMap();
	        name = el.attr('id')
	        cal.init({
		        itemSelector: "#"+name,
        		domain: "month",
	        	subDomain: "day",
		        data: "/graph_data?graph="+name+"&start="+firstDate+"&end="+lastDate,
        		start: new Date(2016, 0, 1),
	        	cellSize: 10,
        		cellPadding: 1,
	        	domainGutter: 2,
		        range: 12,
        		domainLabelFormat: function(date) {
	        		moment.locale("en");
		        	return moment(date).format("MMM").toUpperCase();
		        },
        		cellRadius: 1,
	        	legend: [0, 2, 4, 6, 8, 10]
	        });
        })

Please feel free to ask me questions.

Kind regards,
Maarten

**Comment by wa0x6e** [comment]
Is the first one aborted/cancelled too ?

**Comment by maartendp** [comment]
Indeed. Exactly the same as above.

**Comment by kenshinx** [comment]
Hi, 
I meet the same trouble also.
I am using the latest release JS library and my code highly similar as @maartendp .

![image](https://cloud.githubusercontent.com/assets/129404/19793947/80034db2-9d01-11e6-9100-5a396e1054c4.png)

Thanks a lot for your time.

**Comment by ezraball** [comment]
I'm having the same trouble too. The only difference I see between the two requests is that the first (failed) one doesn't specify mime type in the "accept" request header. The second (successful) one does specify mime type. 

I'm trying to respond to the json request with a Rails app if that makes any difference. 

<img width="740" alt="untitled" src="https://user-images.githubusercontent.com/24692/27501025-f8d772c0-5838-11e7-9c8a-ac50a9087681.png">

**Comment by ezraball** [comment]
By the way, I realized there was an underlying problem with the JSON I was generating on the server side (extra comma at the end). Once I fixed that, the script stopped trying to make the XHR request twice.

**Comment by wa0x6e** [comment]
There was also a double call to XHR request in some data type, so it's not entirely your fault. Bug is fixed on the master
