### ISSUE TITLE
Module Not Loading in AMD

### ISSUE THREAD

**Issue by rakeen** [wa0x6e/cal-heatmap#192]
#### Update:

I was wrong. `cal-heatmap` doesn't seem to be support amd module format.  
I replaced the module format from `amd` to `cjs`(commonjs) and it worked.  

```
System.config({
    map:{
        d3: '/lib/d3',
        'cal-heatmap': '/lib/cal-heatmap'
    },
    packages: {        
        d3: {
            main: './d3.min.js',
            format: 'amd'
        },
        "cal-heatmap": {
            main: './cal-heatmap.js',
            format: 'cjs' // <<==============================
        }
    }
});
```

**Here is a [plukr](http://plnkr.co/edit/ZKkd27eUzYnqZELQnTWI?p=preview) that reproduces the problem.**  
## <br>

<br>

I'm using Systemjs to load the cal-heatmap library in an angular 2 app.

This is what I get if I try to import\* it inside a component.
![image](https://cloud.githubusercontent.com/assets/10359412/13960767/dca3a592-f083-11e5-97de-2d46afc4ada1.png)

*`import * as CalHeatMap from 'cal-heatmap';`

Although I have access to the CalHeatMap object in the browser!
![image](https://cloud.githubusercontent.com/assets/10359412/13960923/77e13bdc-f084-11e5-9664-d0eec573cb8b.png)

My systemjs config:

```
System.config({
    map:{
        d3: '/lib/d3',
        'cal-heatmap': '/lib/cal-heatmap'
    },
    packages: {        
        d3: {
            main: './d3.min.js',
            format: 'amd'
        },
        "cal-heatmap": {
            main: './cal-heatmap.js',
            format: 'amd'
        }
    }
});
```

**Comment by wa0x6e** [comment]
I'm not familiar with SystemJS, sorry

**Comment by rakeen** [comment]
Is it okay to return a function in the amd-module-define callback?
I've seen in other libraries(like [d3js](https://github.com/mbostock/d3/blob/master/d3.js#L9553)) that they return an object. Do you think that might be a problem?

**Comment by rakeen** [comment]
Hi, I was right that cal-heatmap exports a function not an object.

> The issue is that systemjs does not preserve the information that momentjs exports a function. Systemjs simply copy properties of the exported object from a module (a function is an object in JavaScript too).  [SO](http://stackoverflow.com/q/33938561/4437655)

**Comment by wa0x6e** [comment]
So, did you find a workaround, or is the module loading correctly implemented ?

**Comment by rakeen** [comment]
Yes the module loading is correctly implemented :smiley: 
You just have to import the CalHeatMap function instead of the whole object.  

`
import CalHeatMap from '/cal-heatmap'
`

**Comment by rakeen** [comment]
Hi, it seems that I wrong, it is infact not working as a `amd` module.  
I've updated the issue.

**Comment by wa0x6e** [comment]
Fixed in v4
