### ISSUE TITLE
Custom Starting Date

### ISSUE THREAD

**Issue by rakeen** [wa0x6e/cal-heatmap#193]
It [looks](http://wa0x6e.github.io/cal-heatmap/#start) like I can't control the exact starting and ending date. The library by default rounds the date. i.e If my `domain:year` and `subDomain:day`, and if I want to start the calendar from a specific date(not the 1st of Jan), I can't do that.

I want to make it like the github contribution calendar graph.
Any workaround for that for the time being?

**Comment by snumb130** [comment]
Maybe this could be achieved by adding a class to items that are before the start date specified.  Then these could be hidden with CSS.  Similarly to the thought process behind the `.future` class.

**Comment by wa0x6e** [comment]
You could indeed hide the cell via css hidden, that's the only way to do it for now.
Feature is not so easy to implement, due to navigation

**Comment by rakeen** [comment]
I was planning to get the svg and use d3! The css trick is much easier though.
