### ISSUE TITLE
Display empty range in Legend

### ISSUE THREAD

**Issue by outaTiME** [wa0x6e/cal-heatmap#196]
Hi pal, 

Must be usefull to display empty range in the legend (the gray at first) not only the available (defined) legend ranges something like github does:

<img width="162" alt="screen shot 2016-03-27 at 5 27 55 pm" src="https://cloud.githubusercontent.com/assets/140472/14067709/4864770a-f441-11e5-8fea-a79f6c29cc53.png">

thks !!

**Comment by JoshKeegan** [comment]
:+1:

**Comment by dokgu** [comment]
Would love to have this too!

**Comment by wa0x6e** [comment]
Implemented in v4
