### ISSUE TITLE
Unable to reference json file in Data attribute but array list data works 

### ISSUE THREAD

**Issue by ubersant** [wa0x6e/cal-heatmap#197]
Hi, I am incorporating cal-heatmap in my asp.net website and all works fine as long as i am referencing data through an array, initialized as variable above the init method, however things stop showing up as soon as i create new text file in visual studio and rename it as datas-years.json and reference it in 'data' attribute, please help me ?

below is the working code, manually entered data in array and referencing 
![working](https://cloud.githubusercontent.com/assets/11734961/14243086/1502e01e-fa71-11e5-80a1-b2656ab0f07e.JPG)

```
var cal = new CalHeatMap();
      var data = { "1420498800": 20, "1420585200": 40, "1420671600": 60, "1420758000": 1, "1421103600": 2, "1421190000": 90, "1421276400": 1, "1421362800": 1, "1421622000": 1, "1421708400": 1, "1422226800": 1, "1422313200": 1, "1422399600": 2, "1422486000": 1, "1422572400": 1, "1423695600": 3, "1424127600": 2, "1424214000": 1, "1424300400": 3, "1424386800": 1, "1424646000": 2, "1424732400": 1, "1424818800": 2, "1424905200": 2, "1424991600": 1, "1425337200": 1, "1425855600": 4, "1426201200": 2, "1426460400": 2, "1426546800": 1, "1426633200": 2, "1426719600": 1, "1426806000": 1, "1427065200": 1, "1427151600": 1, "1427238000": 2, "1427324400": 1, "1427670000": 2, "1428361200": 2, "1428447600": 2, "1428534000": 3, "1428620400": 3, "1428966000": 2, "1429138800": 2, "1429225200": 1, "1429484400": 2, "1429570800": 1, "1429657200": 2, "1429743600": 2, "1429830000": 3 };

        cal.init({
            data: data,
            itemName: ["volunteer", "volunteers"],
            start: new Date(2015, 0, 1, 1),
            domain: "month",
            subDomain: "day",
            cellSize: 15,
            subDomainTextFormat: "%d",
            range: 12,
            legend: [20, 40, 60, 80],
           

        });
    
```
below is the referencing through separate file, all under visual studio 
![not working](https://cloud.githubusercontent.com/assets/11734961/14243090/20b42abc-fa71-11e5-8d22-841eb049cfad.JPG)

```
var cal = new CalHeatMap();
      
        cal.init({
           
            datatype:JSON,
            data: "datas-years.json",
            itemName: ["volunteer", "volunteers"],
            start: new Date(2015, 0, 1, 1),
            domain: "month",
            subDomain: "day",
            cellSize: 15,
            subDomainTextFormat: "%d",
            range: 12,
            //highlight: new Date(2016, 1, 15),
            legend: [20, 40, 60, 80],


        });
```

I also would like to know what is the best way to convert the date to seconds format, when i impliment it in live, should i ensure that it is added in seconds format to json file or it can be just like 2/26/2015 ? and then convert it into seconds while borrowing from json file ? Please guide me,  thank you

**Comment by wa0x6e** [comment]
Check that your json is a valdi json valid, with the correct http headers. Sending a plain text file, with .json extension will not work.

I don't get your last question, all time in your first example are already in seconds (eg: 1420498800)

**Comment by ubersant** [comment]
@wa0x6e Thank you for the swift reply, admire your work on this . My json file has been attached here, please check if it has any issues, i think it's fine with same data array being pasted in new file named datas-years.json, please find it in attachments 
![json](https://cloud.githubusercontent.com/assets/11734961/14246206/2aa9752e-fa83-11e5-9b23-190666212a25.JPG)

I didn't get your second comment, how do i pass it with correct http headers ? please help

**Comment by wa0x6e** [comment]
Open the developer console, and go to network tab. Then reload your page, and see how the json file is loaded.

This example is for the documentation website page:

<img width="541" alt="screen shot 2016-04-04 at 15 07 56" src="https://cloud.githubusercontent.com/assets/495709/14246269/1ab4dcc8-fa77-11e5-99ad-687aa92f986f.png">

Look how the json file are flagged as JSON.

**Comment by ubersant** [comment]
@wa0x6e Thank you for that image, I could go ahead and check the same and the data attribute was  referenced as follows 
            data:"datas-years.json",

and have attached the image please see, there was 404 error in the status tab 
![capture](https://cloud.githubusercontent.com/assets/11734961/14246463/e670100a-fa84-11e5-9a6b-9dafa0b34403.JPG)

**Comment by wa0x6e** [comment]
Yes, but if you look on the left, you'll see that the file is 404

**Comment by wa0x6e** [comment]
Yes, 404 means file not found.

**Comment by ubersant** [comment]
@wa0x6e Thus you mean it is not found, however I now understood the difference between my image and your image, your image shows status with success but mine 404, how do i go about it now ? That will be very helpful

**Comment by wa0x6e** [comment]
It's an issue with your code, and I can't help you with that

**Comment by ubersant** [comment]
@wa0x6e I don't think so, I am writing it correctly, below is the code 

`<script type="text/javascript">
        var cal = new CalHeatMap();
   
        cal.init({
            data:"datas-years.json",
            itemName: ["volunteer", "volunteers"],
            start: new Date(2015, 0, 1, 1),
            //data: data,
            domain: "month",
            subDomain: "day",
            cellSize: 15,
            range: 12,
            legend: [20, 40, 60, 80],
            subDomainTextFormat: function (date, value) {
                return value;
            }

        });
    </script>`

**Comment by wa0x6e** [comment]
what do you see at http://localhost:3098/datas-years.json ?

**Comment by ubersant** [comment]
@wa0x6e please be here for a while, i have gone a step ahead and will give you details in five minutes

**Comment by ubersant** [comment]
@wa0x6e Hi, actually you rightly asked me the question as it was the lone problem, thing is i had to make some changes in the web.config file in my asp.net project and it started accepting .json format files. That was when i was able to see the json file details in browser path directly...however i am now stuck with error 304, i did bit of research but not understanding what that means exactly. Help please ? 
![capture](https://cloud.githubusercontent.com/assets/11734961/14250206/07a359ce-fa9b-11e5-858e-f48ccf465db5.JPG)

**Comment by wa0x6e** [comment]
Look at http://cal-heatmap.com/datas-years.json

The object should not be enclosed in an array

**Comment by ubersant** [comment]
@wa0x6e okiz, so i remove the boxes around and run ? that shouldn't be a problem ? I tried running after unboxing the JSOn data, however still no luck, not seeing the dates yet highlighted as per json data...corresponding epoch dates are Feb 1st 2016 and Feb 4th 2016, they are not showing up in calendar 

```
<script type="text/javascript">
        var cal = new CalHeatMap();

        cal.init({
      
            data: "http://localhost:3098/datas-years.json",
     
            itemName: ["volunteer", "volunteers"],
      
            domain: "month",
            subDomain: "day",
            cellSize: 15,
            subDomainTextFormat: "%d",
            range: 12,
         
            legend: [20, 40, 60, 80],
        

        });
    </script>
```

**Comment by wa0x6e** [comment]
Seems like an issue that can come from anywhere. Can you reproduce it with a plunker/jsfiddle, or put your demo online ?

**Comment by ubersant** [comment]
@wa0x6e sure i will do that now, but is it necessary to get jquery to make this work ? 
![capture](https://cloud.githubusercontent.com/assets/11734961/14251105/ff9efedc-fa9e-11e5-8e9b-e56cdb32c278.JPG)

**Comment by wa0x6e** [comment]
no

**Comment by ubersant** [comment]
@wa0x6e also the whole calendar disappears the moment i start using itemselector ...and now even setting start date is also making it disappear....when it works it is starting the moneth from april, any reasons ?

**Comment by wa0x6e** [comment]
Please reproduce with a jsfiddle or plunker

**Comment by ubersant** [comment]
@wa0x6e Hi, issue has been reproduced here , calendar is not appearing now, please let me know if i have made any mistakes, thank you 

http://plnkr.co/edit/52D0pF62vdHBPmQNVV5c?p=preview

**Comment by wa0x6e** [comment]
See http://plnkr.co/hzUkCy053AuL0Bv1qRWU

Your data were not in the calendar range.

**Comment by ubersant** [comment]
@wa0x6e  wow, that worked like charm...however i did something like this in jquery...your demo starts wid february...and the itemselector is not working in asp.net, dono why ..if i remove it no loss...pls check dis too and let me know if code is fine ? http://plnkr.co/edit/YcSEWPZ8KfG8BLbzWWgr?p=preview

**Comment by wa0x6e** [comment]
Put the js after the <div> tag

**Comment by ubersant** [comment]
@wa0x6e very much envy your support and time spent on this , how do i get you a beer ? also please gimme some details on getting the prev and next button working, as it is not working here http://plnkr.co/edit/YcSEWPZ8KfG8BLbzWWgr?p=preview

I only added button controls and related js as mentioned in your web page

**Comment by wa0x6e** [comment]
In your Js, put everything inside document ready

**Comment by ubersant** [comment]
@wa0x6e Sorry to start here again after a week almost. I was able to fix the issue with your help and it worked in dynamic environments. 

I am now coming up with reference issue, I copied the whole page to a separate folder inside the project - > localhost:3098/admin 

Admin is the folder under which there are many other pages, I want to run cal-heatmap here in one of the pages, i first created new page inside admin folder and started copying from the working example earlier. However it stopped working in the new folder i copied into , 

is it bcz of file reference ? I changed the data : http://localhost:3098/admin/values.txt  from http://localhost:3098/values.txt to make it accessible in present folder, this text file also gets accessible on browser path but not getting loaded in browser console, what might be the problem ? in just copying the same work to new folder inside project

**Comment by wa0x6e** [comment]
Check the network panel tab

**Comment by ubersant** [comment]
@wa0x6e  I did, not able to see the text file at all..

**Comment by wa0x6e** [comment]
JS code ?

**Comment by ubersant** [comment]
![js](https://cloud.githubusercontent.com/assets/11734961/14389341/dc067c3c-fdcf-11e5-82b0-2863e08818e1.JPG)

**Comment by wa0x6e** [comment]
what's the content of you javascript file ?

**Comment by ubersant** [comment]
values.txt file 
{
"1455494400": 8,
"1456272000": 2,
"1456358400": 1,
"1454716800": 1,
"1454803200": 4,
"1454889600": 7,
"1458345600": 17,
"1458518400": 1,
"1459900800": 2,
"1459987200": 1
}

js file 

 <script>


                   (function ($) {
                       $(document).ready(function () {

                           var dt = [{"1455494400":8, "1456272000":20, "1456358400":4}];

                           var cal = new CalHeatMap();
                           cal.init
                           ({
                               start: new Date(2016, 0), // January 1, 2013
                               range: 12,
                               subDomainTextFormat: "%d",
                               cellSize: 15,
                               itemName: ["volunteer", "volunteers"],
                               domain: "month",
                               subDomain: "day",
                               data: dt,
                               minDate: new Date(2016, 0),
                               maxDate: new Date(2018, 0)
                           });
                           $("#minDate-previous").on("click", function (e) {
                               e.preventDefault();
                               if (!cal.previous()) {
                                   alert("No more domains to load");
                               }
                           });

                           $("#minDate-next").on("click", function (e) {
                               e.preventDefault();
                               if (!cal.next()) {
                                   alert("No more domains to load");
                               }
                           });
                       });

                   })(jQuery);
    </script>

cdn 

    <script type="text/javascript" src="//d3js.org/d3.v3.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.css" />

**Comment by wa0x6e** [comment]
You didn't even load the file in the js code, you're loading your data using a js array

**Comment by ubersant** [comment]
@wa0x6e No the issue was in jquery referencing, silly mistake, I highly admire your support in this issue, made my life easier :) do you accept donations ? please let me know how to make one

**Comment by wa0x6e** [comment]
I have a paypal (wan@kamisama.me)
