### ISSUE TITLE
Next/previous animation issue

### ISSUE THREAD

**Issue by JoshKeegan** [wa0x6e/cal-heatmap#199]
When using the next & previous buttons, ifyou click one of them & then the other before the animation moving the calendar has completed for the first button click, multiple entries will stack up on top of each other on the left and a blank space will be left.
![dashboard - social sense - mozilla firefox](https://cloud.githubusercontent.com/assets/1682204/15355338/f430eec6-1ce9-11e6-8dc5-e5093a44fc88.jpg)

![dashboard - social sense - mozilla firefox_2](https://cloud.githubusercontent.com/assets/1682204/15355350/01a54cbe-1cea-11e6-908a-73f324a66fb6.jpg)

This can be easily reproduced on the demo at the top of http://cal-heatmap.com/

For anyone else having this issue, it can be worked around by disabling the animations (animationDuration: 0).

**Comment by wa0x6e** [comment]
See #134
