### ISSUE TITLE
Make getting d3 object more robust

### ISSUE THREAD

**Issue by JoshKeegan** [wa0x6e/cal-heatmap#200]
I've had a problem using this library alongside another one that declared their own global require function. This is because when you try to get d3, you first check for a require function to load it that way:

```
var d3 = typeof require === "function" ? require("d3") : window.d3;
```

I don't know enough about requireJS to know if there's a standard workaround for this, or a better way of detecting it, but for now I've reversed your test for require, so it tries to use window.d3 first & then falls back to trying to load it via require:

```
var d3 = typeof window === "object" && typeof window.d3 === "object" && typeof window.d3.version === "string" ? window.d3 : require("d3");
```

Any thoughts or help?

**Comment by wa0x6e** [comment]
Related to #180
