### ISSUE TITLE
Highlighting rectangle problem

### ISSUE THREAD

**Issue by JoshKeegan** [wa0x6e/cal-heatmap#201]
When highlighting a rectangle (by hovering or highlight/highlight-now classes) if it is in the top or left row/col the box that gets drawn around it will be missing that side.

E.g.
![cal-heatmap javascript calendar heatmap for time series data - mozilla firefox](https://cloud.githubusercontent.com/assets/1682204/15362551/7571d518-1d0d-11e6-92e5-b073cd72d870.jpg)
![cal-heatmap javascript calendar heatmap for time series data - mozilla firefox_2](https://cloud.githubusercontent.com/assets/1682204/15362557/7e733efe-1d0d-11e6-8052-4af4ff9af516.jpg)
![cal-heatmap javascript calendar heatmap for time series data - mozilla firefox_3](https://cloud.githubusercontent.com/assets/1682204/15362569/89e86c28-1d0d-11e6-940a-14472abcc126.jpg)

Can be reproduced on the demo at the top of http://cal-heatmap.com/

**Comment by snumb130** [comment]
I see the problem with the top border in firefox, but left works fine.  

Both work fine in Chrome.

What browser are you using?

**Comment by JoshKeegan** [comment]
Firefox latest stable (46.0.1)

**Comment by wa0x6e** [comment]
Refer to #108
