### ISSUE TITLE
How to create calender heatmap in multiple rows and multiple columns

### ISSUE THREAD

**Issue by ravish1915** [wa0x6e/cal-heatmap#203]
How to create a calender heatmap with multiple rows and columns?
![cal-heatmap image](https://cloud.githubusercontent.com/assets/11064770/16371085/1fc9c962-3bf9-11e6-84e0-c690fe24eebd.png)
 @wa0x6e

**Comment by wa0x6e** [comment]
You can't. I suggest to create 3 differents instance of the calendar, one for each row. This is a limitation due to navigation

**Comment by wa0x6e** [comment]
Cleaning up old issue
