### ISSUE TITLE
Working on Chrome but Not working properly in Firefox getting below error

### ISSUE THREAD

**Issue by roufs42** [wa0x6e/cal-heatmap#205]
![capture](https://cloud.githubusercontent.com/assets/20205326/16450334/f03ea492-3e19-11e6-865f-a687843df13c.PNG)

**Comment by wa0x6e** [comment]
Everything's working properly on my end. Does the official website not working too ?

**Comment by roufs42** [comment]
It's working on Chrome and IE but its not working on Mozilla and the same case repeats with the chrome on Mac.Official site means cal-heatmap.com working fine.

**Comment by wa0x6e** [comment]
What version of d3.js are you using ? Can you try with the same version as cal-heatmap.com ?

**Comment by roufs42** [comment]
Yup im using same version even though it's showing same error.

**Comment by roufs42** [comment]
I think its something related to time domain.

**Comment by wa0x6e** [comment]
What's your js code ?

**Comment by roufs42** [comment]
Means?

**Comment by wa0x6e** [comment]
Can you show the javascript code you're using ?

**Comment by roufs42** [comment]
means cal-heat one?

**Comment by wa0x6e** [comment]
Yes

**Comment by roufs42** [comment]
[calheat.txt](https://github.com/wa0x6e/cal-heatmap/files/346451/calheat.txt)

**Comment by wa0x6e** [comment]
No, the javascript you're using to instantiate the calendar

**Comment by roufs42** [comment]
(function() {
  var cal = new CalHeatMap();
  cal.init({
    itemSelector: "#animationDuration-a",
    domain: "month",
    subDomain: "day",
    subDomainTextFormat: "%d",
    range: 12,
    cellSize: 30,
    colLimit: 5,
    data: All_metricsData[0],
    columnSize: columnSize,
    rowSize: rowSize,
    start: new Date(2016, 01, 01),
    itemNamespace: "animationDuration-a",
    verticalOrientation: false,
    displayLegend: true,
    legendVerticalPosition: "top",
    legend: Color_ranges,
    domainGutter: 5,
    domainMargin: 10,
    tooltip: false,
    subDomainTitleFormat: {
      'empty': 'There is no data on this day {date}',
      'filled': '{value} on {date}'
    }
  });
})();

**Comment by roufs42** [comment]
Hey waiting for ur replay................

**Comment by roufs42** [comment]
Problem solved tq

**Comment by wa0x6e** [comment]
What was the issue ?

**Comment by roufs42** [comment]
Conversion of time stampvalues
