### ISSUE TITLE
Crash because of incompatible d3 version

### ISSUE THREAD

**Issue by virtualtoy** [wa0x6e/cal-heatmap#207]
In package.json d3 version is specified as `"d3": ">= v3.0.6"`. Starting from v.4 d3 introduced breaking changes. And they break cal-heatmap.

**Comment by outaTiME** [comment]
Forcing d3 version 4.1.0 for now.

4.1.1 version breaks when `d3.time.format("%j")`

**Comment by bakroistvan** [comment]
+1

**Comment by sebastientromp** [comment]
+1, forcing the version to 3.5.17 fixed the issue for me too

**Comment by rcaloras** [comment]
Looks like this was fixed in [3.6.1]( https://github.com/wa0x6e/cal-heatmap/releases/tag/3.6.1) but it hasn't been published yet. Could someone publish this? https://www.npmjs.com/package/cal-heatmap is still showing 3.6.0 as the latest.

**Comment by wa0x6e** [comment]
@rcaloras done

**Comment by wa0x6e** [comment]
Version 3.x of cal-heatmap will be locked to d3 v3.x.

There is no plan to make it compatible for d3 v4, there will be a new branch of cal-heatmap tailored to d3 v4

**Comment by cindyliu-yb** [comment]
any estimated time that for releasing the new branch tailored to d3 v4?
