### ISSUE TITLE
Question about Label Values - Why not aware of data?

### ISSUE THREAD

**Issue by ficus** [wa0x6e/cal-heatmap#216]
Hi,
Trying to set static values for the `legend` property is not working well as the data varies widely by domain.  Is there no way to get the chart to simply divide by the number of legendColors (gradients) using the high datum's value?  Or some scale - just so that the chart responds well to varied data?  Am I missing something?  Thanks!

**Comment by Luiz-N** [comment]
I agree this would be a nice feature... If there was an option that could take the highest and lowest values and then automatically create the gradient of colors in between. If i'm not mistaken I think d3 already offers helper functions for this type of thing.

**Comment by ficus** [comment]
Thanks for sharing that thread.  I'm not too clear on github etiquette when it comes to issues/feedback.  Liked the code and just wanted to share my one take away after having used it.  Maybe this is something that has already been considered and this should just be closed?

**Comment by wa0x6e** [comment]
Using both `legendColors` and `legend` already generates a scale of colors, based on the `legend` array. You just have to specify the min and max colors via `legendColors`.

For the moment, you have to explicitly specify each threshold via the `legend` option, as guessing the highest and lowest value from your data sample is not pertinent, the scale should not be dynamic, even more when the calendar is refreshed dynamically.

But I'm in favor of adding an option to pass an object with `min`, `max` and `steps` to `legend`, so the array can be generated for you.

**Comment by wa0x6e** [comment]
Added in v4

You can now d3.extent your data values, and then pass the it to the legend options, and update the legend and color scale dynamically
