### ISSUE TITLE
Question: days of the week grouping

### ISSUE THREAD

**Issue by niconoe** [wa0x6e/cal-heatmap#219]
Hello,

I'd like to display statistics about a parking usage... It would therefore make sense to group data by days of the week, and then shows occupation for each hour, so we can for example immediately see that Monday 10am is more busy than Tuesday 3pm. Is that currently possible ? I guess we'd need a "days of the week" domain with the "hour" subdomain, right?

**Comment by wa0x6e** [comment]
Doesn't week domain and day subDomain solve your problem ?
