### ISSUE TITLE
cal-heatmap-container svg height not proper

### ISSUE THREAD

**Issue by ankitrg** [wa0x6e/cal-heatmap#221]
I have a parent div and I've set a minimum height to it as 400px. The heatmap svg which is generated has a height which is very less, even the content are not visible correctly.

If I go the dev tools and increase the height of the svg it becomes visible.

I also saw that it has something to do with the range, if I increase/decrease the range, this height varies. Can you please help me with this?

**Comment by wa0x6e** [comment]
You may want to look at http://cal-heatmap.com/#domainDynamicDimension
