### ISSUE TITLE
When legend starts with 0, the max legendColor will be not set (become black)

### ISSUE THREAD

**Issue by NeoCat** [wa0x6e/cal-heatmap#224]
When the legend starts with 0, like  [0,20,40,60,80], and legendColor is set to 2 colors, the last range segment ("more than 80" in the example) are not colored, which will be drawn with black color.

![before](https://cloud.githubusercontent.com/assets/145817/21224385/4edaa864-c30f-11e6-88fa-ddcd8dfdd9a0.png)

With the patch in the pull request #223, the color will be set as intended.

![after](https://cloud.githubusercontent.com/assets/145817/21224469/c067a46e-c30f-11e6-96a7-00fc9e88712b.png)

**Comment by maurop123** [comment]
I've still got the issue. I couldn't reproduce in a jsfiddle cause the fix isn't in the latest cdn, but here's the screenshot.

![screenshot 2017-08-16 23 50 23](https://user-images.githubusercontent.com/1924900/29395281-bdec73de-82dd-11e7-971b-f0fd544f0008.png)

with this code

```
const cal = new CalHeatMap();
    cal.init({
      data: '/static/sample-datas-hours.json',
      itemSelector: '#cal-heatmap',
      start: new Date(2000, 0),
      legend: [0,10,20,30,40],
      legendColors: {
        empty: "#ffffff",
        min: "#dae289",
        max: "#3b6427",
      }
    });
```

**Comment by maurop123** [comment]
got it working by adding this style

```
.domain-background {
  opacity: 0;
}
```

Hope that helps!

![screenshot 2017-08-17 12 37 30](https://user-images.githubusercontent.com/1924900/29423199-dbe62694-8348-11e7-8215-47ee43a7da79.png)
