### ISSUE TITLE
How introduce  modulo on subDomain

### ISSUE THREAD

**Issue by Maujard** [wa0x6e/cal-heatmap#226]
Hi,
How to reduce the subDomain in modulo like  :

domain="hour"
subDomain= "min"
subDomainModulo="5"

I expect one square for each time modulo 5 minutes. For one hour only 60/5 = 12.
subDomainModulo in course = 1  by default.

Or 
subDomain ="min * 5" 

 Thank a lot
Dominique

**Comment by wa0x6e** [comment]
It's in consideration, see #164
