### ISSUE TITLE
Hide domains without dates

### ISSUE THREAD

**Issue by stevelacy** [wa0x6e/cal-heatmap#227]
Is there current support for hiding domains without any data?
Example, hide months without any data such as this:
![selection_00120170315 22 15](https://cloud.githubusercontent.com/assets/5648999/22610845/bbdb2880-ea24-11e6-90b9-6c8332499057.png)

**Comment by wa0x6e** [comment]
No, that will defeat the purpose of the heatmap concept

**Comment by soke1556** [comment]
I really need to do this. I need to hide domains and only show those that are relevant to the use case. Any workaround?

**Comment by stevelacy** [comment]
I just switched off from this to a home grown one, tiled svg's without the domain break
