### ISSUE TITLE
Week only with week highlight

### ISSUE THREAD

**Issue by papyr** [wa0x6e/cal-heatmap#228]
Hi your control seems very creative, I am trying to show weekly course schedules for students.

1. I need some guidance on, **which format is the best to present the information**. The students pick the week (showing dates and week number), preferably 8 weeks into the past. I want to highlight the entire week, select and send the data back, as the first day of the week like Monday or week number.
2. What date format should I send to the cal-heatmap

**Comment by wa0x6e** [comment]
I don't quite get what you want to achieve here.
You can pass an array of date object to the highlight() method. But the heatmap is one-way, the user can not manipulate it to send back events to you.
