### ISSUE TITLE
update() method to refresh the map?

### ISSUE THREAD

**Issue by BigChief45** [wa0x6e/cal-heatmap#229]
The [`update()`](http://cal-heatmap.com/#update) method requires new data as arguments to update the calendar with the new data. 

I believe that it would be nice to be able to call `update()` with no arguments to refresh the calendar, making it send another request for the data just as when it was initialized.

Currently calling `update()` with no arguments simply makes the calendar go blank.

**Comment by wa0x6e** [comment]
Why don't you just pass your data again to update() ?

**Comment by BigChief45** [comment]
Yes that is an obvious solution. But wouldn't you say it would be nice for a call to `update()` with no arguments to do this as well? I can work on a PR.
