### ISSUE TITLE
Multi selection of cells

### ISSUE THREAD

**Issue by dorcohen8** [wa0x6e/cal-heatmap#231]
Thanks for the amazing heatmap!
Can I select multiple cells by using a mouse drag? for example:

![image](https://cloud.githubusercontent.com/assets/3125971/25313691/3bed823e-283c-11e7-855b-f9f3881ed0cc.png)

**Comment by wa0x6e** [comment]
Not for the moment. If mouse drag event is added one day, it will be used to go to the next and previous domain.
