### ISSUE TITLE
I have been using Cal-Heatmap to create a calendar. I would like to only visualize the hours between 8am and 9am on that day. Is there any way to do this through cal-heatmap?

### ISSUE THREAD

**Issue by pvakani123** [wa0x6e/cal-heatmap#232]

**Comment by wa0x6e** [comment]
Use the hour domain with min subdomain, with 8am as start, and 1 as range

**Comment by pvakani123** [comment]
I mean I want a month in the domain and date in the subdomain. In my dataset, the data is recorded every hour and cal-heatmap is adding up all the data for a particular date. So, I was thinking if I can target particular hour for a day with the month in the domain and day as a subdomain and only show a data for the particular hour for the particular day.

**Comment by wa0x6e** [comment]
No you can't. Only way is to remove the unwanted data from the source, before passing it to the calendar.

Either you do that directly on your source, or you can use the afterLoad callback (http://cal-heatmap.com/#afterLoadData) to do it. Do a for loop, and keep only the timestamps you want. There's some math involved.

**Comment by wa0x6e** [comment]
Closing since inactive
