### ISSUE TITLE
How to replace the word ‘on’ in the tooltip?

### ISSUE THREAD

**Issue by laiwenqiang** [wa0x6e/cal-heatmap#233]
I try to use 
```itemName: ["个贡献<br/>","个贡献<br/>"]``` and ```subDomainDateFormat: "%Y年/%m月/%d日"``` 
to conver the info I want to show. 
But，how can I replace the word ‘on’ ？
![Uploading Snip20170530_8.png…](http://oqgq7175e.bkt.clouddn.com/Snip20170530_8.png)

**Comment by wa0x6e** [comment]
See {connector} in http://cal-heatmap.com/#subDomainTitleFormat

**Comment by laiwenqiang** [comment]
3Q！
