### ISSUE TITLE
Cal-Heatmap fires twice data request and xhr request fail on first, response shows NaN items in calendar

### ISSUE THREAD

**Issue by FFMChris** [wa0x6e/cal-heatmap#236]
Hey there,..

I am using cal-heatmap with an 6 month view. I do the call to mysql using php codeigniter and convert the utc string prior to hit the mysql. The response looks fine and as defined.

But my xhr fires twice and the first is failing, also i get an `NaN items` display on hover where it should say i.e. 1.

Below shows the xhr fail:

<img width="572" alt="cal_heatmap" src="https://user-images.githubusercontent.com/30076145/28067598-2b5d1f94-6642-11e7-8086-1d7e9f781a19.png">

Below is the response from the second succeeded event:

<img width="484" alt="cal_heatmap_response" src="https://user-images.githubusercontent.com/30076145/28067629-44247324-6642-11e7-82d2-e80569cbced8.png">

<img width="298" alt="cal_heatmap_response_object" src="https://user-images.githubusercontent.com/30076145/28067638-4a34a928-6642-11e7-9ae9-f47d97fff819.png">

Below is the NaN display:

<img width="192" alt="cal_heatmap_nan" src="https://user-images.githubusercontent.com/30076145/28067682-8e1f02aa-6642-11e7-886c-a21125b932ae.png">

**Comment by wa0x6e** [comment]
Twice xhr event has been fixed in the master. Can you try ?

**Comment by FFMChris** [comment]
I am using this version:  cal-heatmap v3.6.2 (Mon Oct 10 2016 01:36:42)

**Comment by FFMChris** [comment]
Sorry, i now use the one from the SRC folder and it works. It doesn't do the double xhr. Thanks,..

Any hint about the NaN? It looks like my response is not numeric for cal-heatmap to handle. How should i modify the php to get the results in desired format? 

I am currently using below:

```
$this->db->select('unix_timestamp(STR_TO_DATE(date_start, "%Y-%m-%d")) dateStampSecs,count(*) as value');
        $this->db->from('calendar');
        $this->db->where('date_start >=',$start);
        $this->db->where('date_end <=',$end);
        $this->db->group_by('unix_timestamp(STR_TO_DATE(date_start, "%Y-%m-%d"))');
        $query = $this->db->get()->result();
        //$query->result();
        
        $dateStampSecs = array_column($query, "dateStampSecs");
        $value = array_column($query, "value");
        $result = array_combine($dateStampSecs, $value);
        print json_encode($result,JSON_PRETTY_PRINT);
```

**Comment by wa0x6e** [comment]
Remove the quote around the nuneric value

**Comment by FFMChris** [comment]
I did it. I used print JSON_NUMERIC_CHECK im my encode.

`print json_encode($result,JSON_NUMERIC_CHECK);`
