### ISSUE TITLE
Aggregated Day/Week view?

### ISSUE THREAD

**Issue by victorhooi** [wa0x6e/cal-heatmap#238]
Hi,

Is there any way to show a aggregated week/day view? 

For example:

<img width="1026" alt="screen shot 2017-08-17 at 18 53 50" src="https://user-images.githubusercontent.com/243499/29404070-722d911c-837d-11e7-9089-859572e25e94.png">

http://bl.ocks.org/tjdecke/5558084

(i.e. rather than for a single week, show the overall day/week heatmap for multiple weeks, aggregated)

**Comment by wa0x6e** [comment]
Now possible in v4, with the custom templates injection

**Comment by empireshades** [comment]
I don't suppose someone can throw together a quick example of how this could be done using custom templates? I'm looking for something similar, basically my domain is day and subdomain is hour but I am looking to have all hours in one column like in the above illustration. Thank you.
