### ISSUE TITLE
Any way to determine size

### ISSUE THREAD

**Issue by eMerzh** [wa0x6e/cal-heatmap#241]
Hi, 
i want my chart to fit my container size, but i can't find a way to make i bigger or smaller...
did i miss smth ?

**Comment by wa0x6e** [comment]
The chart is not responsive yet, and have fixed dimension.
You could center it, so it does not look too ugly

**Comment by eMerzh** [comment]
Hey,
many thanks for your quick reply (nice lib btw!)
I'm not really talking about "responsiveness" like grow with container or display less/more info regarding the screen size...
but let say i want the chart to take 1500px on 100px , is there a way to do that or is it the "responsiveness" you are talking about ?

Thanks

**Comment by wa0x6e** [comment]
All dimensions are static. You can either change the cells size, or display more columns

**Comment by seanfcarroll** [comment]
[This post](http://www.cagrimmett.com/2016/07/04/posts-heatmap-calendar.html) deals with the size / responsiveness issue.

**Comment by sataqi** [comment]
@wa0x6e 
> You could center it, so it does not look too ugly

any help on doing this, I tried with CSS on parent `div` but didn't work.

**Comment by svagier** [comment]
> [This post](http://www.cagrimmett.com/2016/07/04/posts-heatmap-calendar.html) deals with the size / responsiveness issue.

The link is out of date, check this repo: https://github.com/cagrimmett/jekyll-tools#posts-heatmap-calendar
@sataqi , this may help you

**Comment by wa0x6e** [comment]
the resize event in v4 is now returning the new width/height, as well as the old width/height.

You can add a eventListener on the window resize event, then use it to know whether the window is much larger than the calendar, and change increase the number of calendar domains if necesary.
