### ISSUE TITLE
Tooltip not shown completely at the top

### ISSUE THREAD

**Issue by nwang57** [wa0x6e/cal-heatmap#245]
If you check this [https://jsfiddle.net/ea6gkqLh/2/](https://jsfiddle.net/ea6gkqLh/2/). The tooltip for the very first item will be hidden behind other divs. Is there a way to let the tooltip show above?

**Comment by wa0x6e** [comment]
The issue seems to be from jsfiddle, using iframe. Did you get the same issue with you real code ?

**Comment by nwang57** [comment]
I spot the problem. It is because I have "overflow: hidden" in the parent div in my code. Thanks for your quick reply.
