### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by Misterfluff** [wa0x6e/cal-heatmap#246]
It's me again ... I created a fiddle -https://jsfiddle.net/Misterfluff/8k0crvc9/
This works great. The only problem is that the date slips by one day. The first value should be 40 for April 1. The value represented is for April 2 (56). I know there is a function to fix this but I do not understand how to incorporate it. The function looks like this:
afterLoadData: function (timestamps) {
  var offset = new Date().getTimezoneOffset() * 60;
  var results = {};
  for (var timestamp in timestamps) {
    var commitCount = timestamps[timestamp];
    timestamp = parseInt(timestamp, 10);
    console.log(timestamp)
    results[timestamp + offset] = commitCount;
  };
  return results;
}
Since I already have an afterLoadData statement, how would I incorporate this?
Sorry for so many questions ... still learning :-)

**Comment by milosb793** [comment]
Man, you saved my (few) days with that timestamp acrobatic! :D

**Comment by wa0x6e** [comment]
I do see the 40 for April 1.

I guess it's a timezone issue, so related to #105 
v4 will use moment-timezone to handle all the dates, and add support for timezone
