### ISSUE TITLE
Scrolling views causes artifacts

### ISSUE THREAD

**Issue by zewt** [wa0x6e/cal-heatmap#247]
When I scroll the view back and forth, the entries wrap around to the wrong place.   Just press prev and next a few times on http://cal-heatmap.com/#previousSelector.  It happens in Chrome and Firefox.  Not sure if it's related to the current time (Feb 1 2 AM UTC-0600, just after the month changed over).

(I guess this project isn't in active development, with no commits since June and major bugs like #105 open since 2014, but I thought I'd pass this along anyway...)

**Comment by glutanimate** [comment]
Seeing the same issue here, both on Chrome 69.x and Firefox. I seem to be able to trigger this more reliably when scrolling through the views quickly. Might be an animation issue?

Here's to hoping that @wa0x6e or someone else will be able to pick up development again. cal-heatmap really is the best solution in its category.

(@wa0x6e, thanks for all the work you've put into this project, by the way! It's really appreciated)

**Comment by wa0x6e** [comment]
Just to make sure, you're talking about the issue when you click on NEXT or PREVIOUS quickly, without giving the time for the sliding animation to complete ?

A quick temporary fix for that particularly issue is to disable the sliding animation

**Comment by wa0x6e** [comment]
Closing, in favor of #134

**Comment by glutanimate** [comment]
@wa0x6e Yes, exactly. Thanks, I'll consider disabling the animation (though it would really be a shame as it looks beautiful!).
