### ISSUE TITLE
Cannot find module "d3/index"

### ISSUE THREAD

**Issue by FatManiac** [wa0x6e/cal-heatmap#254]
Hi,

i'm trying to test the cal-heatmap module but i get Cannot find module "d3/index"
i have d3 version below 4.0
i'm working on Angular5 and Ionic 3

Thank for your work

**Comment by wa0x6e** [comment]
How did you import d3 ?

**Comment by gabri3l0** [comment]
> I've fixed the issue, i don't really remember how it was a long time ago but thanks for your answer, i ended doing my calendar heatmap from scratch, it was fun :)

How do you import the module, what do you install? and how to import it, pls help me
