### ISSUE TITLE
Is there a way to revert the calendar direction ?

### ISSUE THREAD

**Issue by disk91** [wa0x6e/cal-heatmap#258]
Actually the calendar is displayed with older time on the left and time growing on the right. I would like to have the most recent period on the left and older time on the right.
Is that possible to do ?
(Not seen in the documentation, seen some Global in the code for selecting navigation direction)

**Comment by wa0x6e** [comment]
As of now, it’s not possible. What will be the point / use case ?
Logically, calendar is always read from left to right.

**Comment by wa0x6e** [comment]
See #111
