### ISSUE TITLE
subDomain interval?

### ISSUE THREAD

**Issue by sanjeevbeekeeper** [wa0x6e/cal-heatmap#259]
Is it possible to control the `subDomain `interval. My `domain: hour `_(8:00 am and 9:00 am)_  and `subDomain: min` . The subDomains displays every 10 sec interval. Is it possible to have every 5 or 10 min interval?
By the way, the cal-heatmap is wonderful!

**Comment by wa0x6e** [comment]
It's in the todo list.
Related to #164
