### ISSUE TITLE
Cross off date possible with two subDomainTextFormat?

### ISSUE THREAD

**Issue by nipunsadvilkar** [wa0x6e/cal-heatmap#260]
Hi @wa0x6e, Thanks for such a great library!

I was curious to know if it is possible to have two `subDomainTextFormat`.

I wanted to do something like this:

![redxs](https://user-images.githubusercontent.com/15062408/47454403-c6102280-d7ec-11e8-8a64-7381a8dfff88.jpg)

Any inputs from anyone would be of great help!

Thanks,
Nipun

**Comment by wa0x6e** [comment]
You can pass a function to `subDomainTextFormat` to achieve what you want

**Comment by wa0x6e** [comment]
Added in v4, formatter function now have an additional argument, which is the SVG node of the text. Use it append more svg element to the cell
