### ISSUE TITLE
Be able to change the language for the months

### ISSUE THREAD

**Issue by ghost** [wa0x6e/cal-heatmap#261]
My website is only in Swedish. Therefore it looks a bit odd when the months for the heatmap are in English. I've looked at the source code and the documentation, but it seems that the names of the months are not hardprinted into the script. The names are generated? Anyway. Please, add the support for multi language for the months!

**Comment by wa0x6e** [comment]
See https://cal-heatmap.com/#domainLabelFormat and the whole i18n category in general

**Comment by edgren** [comment]
Thanks. But the locale for momentjs is not working - it still showing in English.

```JS
	moment.locale("sv");
	var datas = $('#cal-heatmap').attr('data-fetch').split(',');
	var cal = new CalHeatMap();
	cal.init({
		domain: "month",
		data: datas,
		afterLoadData: parser,
		start: new Date(2018, 0),
		minDate: new Date(2017, 11),
		cellSize: 13,
		range: 12,

		domainLabelFormat: function(date) {
			return moment(date).format("MMMM");
		}
	});
```

**Comment by wa0x6e** [comment]
Just tested, and it works

Don't forget to load momentjs with all the locales
