### ISSUE TITLE
insert custom text inside item or on over

### ISSUE THREAD

**Issue by weedkiller** [wa0x6e/cal-heatmap#264]
Hello, how can we insert custom text like the name of a person who worked on a day

**Comment by wa0x6e** [comment]
Use the `subDomainTextFormat` function to insert the text on calendar creation, then use some CSS to hide it, and show only on hover

```
.graph-subdomain-group .subdomain-text {
display: none;
}

.graph-subdomain-group g:hover .subdomain-text {
display: block;
}
```
