### ISSUE TITLE
Accessing click event from onClick

### ISSUE THREAD

**Issue by kwayebopp** [wa0x6e/cal-heatmap#265]
The `onClick` option takes a function parametrized by the date and the value associated with the date only. I'm not sure about how other people feel, but I think it would be very useful to have the Event data as an additional parameter. In my use case, I'd like to know the target of the event because I display several calendars at once.

so instead of
```
this.cal.init({
  ...
  onClick: (date, number) => {...}
  ...
})
 
```

something like 

```
this.cal.init({
  ...
  onClick: (clickEvent, date, number) => {...}
  ...
})

```

**Comment by wa0x6e** [comment]
Added in v4
