### ISSUE TITLE
interpolateHcl produces colors that are hard to understand

### ISSUE THREAD

**Issue by hanzhaodeng** [wa0x6e/cal-heatmap#266]
d3.interpolateHcl doesn't produce intuitive colors for a heat map. For example, if we want to have legendColors transitioning from white to red, it will go through green.

You can try in the legend playground: https://cal-heatmap.com/#legendColors
Set color range to #ffffff and #ad001d.
Personally I think this transition should be more and more red. Green doesn't make sense to me personally.
Also potentially, if you want your UI to only have different shades of red as a design spec, this will break it.

Can we add options to let user to decide which transition to apply? Potentially d3.interpolateRgb seems like a better default for doing transitions.

**Comment by alanmels** [comment]
I second the request to change the algorithm as currently even taking an example of GitHub activity calendar colors

![Screenshot from 2021-01-28 19-09-25](https://user-images.githubusercontent.com/56604405/106222266-660f4000-619c-11eb-8209-d1c1f30e9432.png)

as:

```
legendColors: ["#ebedf0","#216e39"],
```

gives:

![Screenshot from 2021-01-28 19-11-13](https://user-images.githubusercontent.com/56604405/106222386-a8388180-619c-11eb-881a-642cd27fef32.png)

and it's really hard to differentiate the cells.

I've played with lot's of color combination and, unfortunately, none of them have enough contrast between threshold colors.

Using css is not always suitable. For example, if you want to let users choose their colors of preference via UI.

**Comment by wa0x6e** [comment]
Fixed in v4, now using https://observablehq.com/@d3/color-legend
