### ISSUE TITLE
TypeError: Cannot read property 'format' of undefined

### ISSUE THREAD

**Issue by jaepetto** [wa0x6e/cal-heatmap#271]
I have a web page (Django) where both d3 and cal-heatmap are referenced:
```
<script src="{% static 'js/vendors/d3/d3.js' %}"></script>
<script src="{% static 'js/vendors/cal-heatmap/cal-heatmap.js' %}"></script>
```

Both scripts are loaded successfully. However, I get the following message in the console:
"TypeError: Cannot read property 'format' of undefined"

This exception is triggered by:
https://github.com/wa0x6e/cal-heatmap/blob/0b594620104e0b11a94cc45feb0a76b58a038e0e/cal-heatmap.js#L2009

**Comment by wa0x6e** [comment]
What is the d3 version ? How are you initializing the script ?

**Comment by jaepetto** [comment]
I did use d3.js v6.0.0 (downloaded from d3 site).
Using it from a CDN (as per your documentation - v3 -) works OK:
https://codepen.io/jaepetto/pen/oNLxPqY

sorry with the annoyance...

**Comment by wa0x6e** [comment]
Latest d3 version is not supported yet

**Comment by jaepetto** [comment]
Thanks @wa0x6e for your quick reply and this library.
