### ISSUE TITLE
Display more item information upon triggering onClick

### ISSUE THREAD

**Issue by alanmels** [wa0x6e/cal-heatmap#273]
I'm trying to provide more information upon clicking on the calendar cells than simply the number of items on a certain date. In particular, while collecting the data for calendar my scripts prepares more useful information on each item. 

According to https://cal-heatmap.com/#data-format the data format should be:

```
{
	"timestamp": value,
	"timestamp2": value2,
	...
}
```

Would be wonderful if we could feed more information associated with each timestamp and then retrieve that information with [`onClick`](https://cal-heatmap.com/#onClick) event. For example, if the format was something like:

```
{
	"timestamp": [value, object],
	"timestamp2": [value2, object2],
	...
}
```
then we could put all kind of things related to a timestamp into `object` and retrieve the object information with events like `onClick`.

If the data format wont' change, then any recommendation how to display additional information associated with the timestamp upon clicking the calendar cell?

**Comment by swk23C8** [comment]
Hey! I was wondering if you found a work around way for this. I'm approaching this problem in a hacky way and its not looking too clean :/

**Comment by wa0x6e** [comment]
You can use your custom data
```
var data = {
	"timestamp": [value, object],
	"timestamp2": [value2, object2],
	...
}
```
and use the `afterLoadData` (https://cal-heatmap.com/#afterLoadData) event to format them to the expected format.

As the `onClick` event is a function with the cell date as first argument, you can use it to retrieve the associated line in your original data object.

**Comment by C-Aniruddh** [comment]
@wa0x6e now that `afterLoadData` is gone, is there any way to do this?

**Comment by C-Aniruddh** [comment]
@wa0x6e , I have implemented that in place. However, I have three fields coming from my data source `value`, `timestamp`, `id`. For parsing, I parse the `x` to `timestamp` and `y` to `value`. What can I use for `id`?

**Comment by wa0x6e** [comment]
You can ignore it

**Comment by C-Aniruddh** [comment]
Oh I think I am conveying the usecase in a wrong way. I need to transmit the `id` to the `click` event.

**Comment by wa0x6e** [comment]
I see, the calendar does not save any extra data.

For your use case, save your data in an external variable, before sending it in the calendar.
The click event will return a timestamp, which you can use to search your original variable, to extract the data you want to use.

```
const data = [{ timestamp: 000, id: 1, value: 3}];

cal.paint({ data: { source: data } });
```

then onClick, you do a search inside your `data` with the timestamp returned by the click event
