### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined (setting 'range')

### ISSUE THREAD

**Issue by ChiaYuSu** [wa0x6e/cal-heatmap#286]
There is a error at cal-heatmap@4.0.0-beta.1 by using cdn
```html
<head>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <script src="https://unpkg.com/cal-heatmap@4.0.0-beta.1/dist/cal-heatmap.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/cal-heatmap@4.0.0-beta.1/dist/cal-heatmap.css"></script>
</head>

<script>
    const cal = new CalHeatmap();
    cal.paint();
</script>
```

problem
![image](https://user-images.githubusercontent.com/26423040/210338294-96fea5e4-a49c-40df-bc56-ba52927a049b.png)
![image](https://user-images.githubusercontent.com/26423040/210338339-b51fb8ab-e72e-4f60-a3e6-2ba02ae3244e.png)

**Comment by wa0x6e** [comment]
Seems like there is an error looking for the moment library

Quick fix for now is to include it in your <head>

`<script src="https://momentjs.com/downloads/moment-with-locales.min.js"></script>`

**Comment by ChiaYuSu** [comment]
Ok, thank you.

**Comment by wa0x6e** [comment]
beta 2 has been released
