### ISSUE TITLE
Some errors occur at cal-heatmap@4.0.0-beta.2

### ISSUE THREAD

**Issue by ChiaYuSu** [wa0x6e/cal-heatmap#292]
```html
<script src="https://unpkg.com/cal-heatmap@4.0.0-beta.2/dist/plugins/Timezone.min.js"></script>

// Choose one of the following choices, depending on your need
<script src="https://momentjs.com/downloads/moment-timezone-with-data.min.js"></script>
<script src="https://momentjs.com/downloads/moment-timezone-with-data-1970-2030.js"></script>
<script src="https://momentjs.com/downloads/moment-timezone-with-data-10-year-range.js"></script>
```

There is the bug when I using `moment.js`, I randomly choose any of the following choices, there will be similar to the following error.
![image](https://user-images.githubusercontent.com/26423040/211340411-968ba600-f26c-416b-9e66-7e3661c6eac8.png)

And another question, I didn't set the start date, but the date is not from 2023/01/01, but from 2022/12/31. I think it should be a time difference problem, but I would like to ask how to adjust the time zone I want.
![image](https://user-images.githubusercontent.com/26423040/211340130-320578c0-46fc-48d6-9f6a-b7dcd280947f.png)

**Comment by wa0x6e** [comment]
Regarding #1, seems like an issue regarding finding the moment library when using moment-timezone.

Quick fix for now is to also explicitly include it, before the moment-timezone script

```
<script src="https://momentjs.com/downloads/moment.min.js"></script>
```

Regarding #2, this is normal, and just a timezone formatting issue. The calendar is using your local timezone, but the tooltip is showing the UTC timezone, hence the difference.

You can tell the tooltip to use your local timezone with:

```
cal.paint({}, 
[
  Tooltip,
  {
    text: (d) => new Date(d)
  }
]
);
```

Tooltip is showing date in UTC format by default.
