### ISSUE TITLE
I would like to ask some example about click event

### ISSUE THREAD

**Issue by ChiaYuSu** [wa0x6e/cal-heatmap#295]
I would like to ask some example about click event, how can I get the highlighter value (include year, month, day and value) in below pic, thank you.

![image](https://user-images.githubusercontent.com/26423040/211584485-6c78624c-a319-4523-9f77-4bc2b90d6585.png)

**Comment by ChiaYuSu** [comment]
Thank you, but how to get the value in my data.
When I click `2023-01-01`, how can I get both date and value.

```js
var data = [
    { date: '2023-01-01', value: 327 },
    { date: '2023-01-03', value: 61 },
    { date: '2023-01-07', value: 74 },
];
```

**Comment by wa0x6e** [comment]
It's the third argument

```
cal.on('click', (event, timestamp, value) => { return new Date(timestamp) + ' => ' + value; });
```

**Comment by ChiaYuSu** [comment]
Got it, but in my situation, my value will console `value = 0` in `date = 2023-01-01`, but console `value = null` in date = `2023-01-10`, but I wonder answer is if `date = 2023-01-01` and `value = 327`, thank you.

**Comment by wa0x6e** [comment]
Can you share the paint() code ?

**Comment by ChiaYuSu** [comment]
```js
cal.paint({
    data: { source: data, x: 'date' },
    range: 12,
    date: { 
        start: date,
    },
    domain: {
        type: 'month',
        subLabel: {
            width: 30,
            textAlign: 'start',
            text: (moment) => moment.weekdaysShort(true).map((d, i) => i % 2 == 0 ? '' : d),
        },
    },
    subDomain: { 
        type: 'day',
        radius: 2,
        height: 15,
        width: 15,
    },
    itemSelector: '#cal-heatmap',
}, 
[[Tooltip, {
    text: (d) => formatDate(d)
}]]);
```

**Comment by wa0x6e** [comment]
data: { source: data, x: 'date' },

should be 

 data: { source: data, x: 'date', y: 'value' },

**Comment by ChiaYuSu** [comment]
It fixed.
Thank you for helping me debug.
