### ISSUE TITLE
[Wish] Want to know if legend can be designed to be the same as github

### ISSUE THREAD

**Issue by ChiaYuSu** [wa0x6e/cal-heatmap#298]
As the question

Current Design
![image](https://user-images.githubusercontent.com/26423040/211737703-bd734229-d1f0-46d4-9103-ea9166baad34.png)

GitHub Design
![image](https://user-images.githubusercontent.com/26423040/211737767-2663998b-a32a-4cba-a1d7-c79df351aaa4.png)

**Comment by wa0x6e** [comment]
It was available in v3, will be back before releasing final v4, as plugin

**Comment by ChiaYuSu** [comment]
Ok, thank you.
Looking forward to the final release of v4.
