### ISSUE TITLE
locale 'zh-tw' is not work

### ISSUE THREAD

**Issue by ChiaYuSu** [wa0x6e/cal-heatmap#303]
I have include `<script src="https://cdn.jsdelivr.net/npm/dayjs@1/locale/zh-tw.js"></script>` in the `<head></head>` already, and I have either add script `locale: 'zh-tw'` in the date structure.

![image](https://user-images.githubusercontent.com/26423040/216569921-c8c15909-c3dd-430b-ac45-db1b019eb770.png)
![image](https://user-images.githubusercontent.com/26423040/216569947-21e81342-5b5c-4fdd-8294-167f433f5d7b.png)

**Comment by wa0x6e** [comment]
Did you add it after the cal-heatmap.js ?

**Comment by ChiaYuSu** [comment]
Yes

**Comment by ChiaYuSu** [comment]
import list
```html
<script src="https://d3js.org/d3.v7.min.js"></script>
<script src="https://unpkg.com/cal-heatmap@4.0.0-beta.4/dist/cal-heatmap.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/cal-heatmap@4.0.0-beta.4/dist/cal-heatmap.css"></script>
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/cal-heatmap@4.0.0-beta.4/dist/plugins/Tooltip.min.js"></script>
<script src="https://unpkg.com/cal-heatmap@4.0.0-beta.4/dist/plugins/Legend.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/dayjs@1/locale/zh-tw.js"></script>
```

**Comment by ChiaYuSu** [comment]
The information will be one day different from the actual time in Taiwan (UTC+8).

**Comment by wa0x6e** [comment]
Locale and timezone are two separate thing.

Do you have a data sample, and your js code for the calendar ?

**Comment by ChiaYuSu** [comment]
![image](https://user-images.githubusercontent.com/26423040/217007707-f0acb040-0e5a-4211-b896-1baa98005146.png)

```js
var data = [
    { date: '2023-02-01', value: 327, info: 'test' },
    { date: '2023-02-02', value: 98 },
    { date: '2023-02-03', value: 74 },
    { date: '2023-02-04', value: 115 },
];
```

**Comment by wa0x6e** [comment]
Did you set the timezone option ?

**Comment by ChiaYuSu** [comment]
It means set 
```js
date: {
        start: getYear + '-01-01',
        timezone: 'zh-tw',
},
```
?

Yes, I have set it, but it occurs error.

![image](https://user-images.githubusercontent.com/26423040/217009024-3d148586-3ac8-4b9c-b375-0fb67323baa8.png)

**Comment by wa0x6e** [comment]
`Zh-tw` is a locale, not a timezone

Taiwan timezone is `Asia/Taipei`

**Comment by ChiaYuSu** [comment]
yes, it fixed, thank you.
but the heatmap is still one day different from the actual data.

**Comment by ChiaYuSu** [comment]
Yes.
And, the server is at local server now, so i think actually is not the server timezone problem.

**Comment by wa0x6e** [comment]
Looks like a timezone issue while parsing the date value, I will make some tests

**Comment by wa0x6e** [comment]
See #306 for issue about data one day behind
