### ISSUE TITLE
Painted dataset is one interval behind

### ISSUE THREAD

**Issue by wa0x6e** [wa0x6e/cal-heatmap#306]

**Comment by ChiaYuSu** [comment]
I remember the previous version using `moment.js`, it seems that there is no such problem, to provide you with reference

**Comment by ChiaYuSu** [comment]
Hi, thank you for fixing this bug and releasing beta 7 as soon as possible!
However, there are still some bugs in my environment, so please help me to check again


My console screen
![image](https://user-images.githubusercontent.com/26423040/219255252-93ad4451-6ecc-4a17-bfa4-8e4d2cadc8e6.png)

Import script
```html
<!-- Heatmap -->
<script src="https://d3js.org/d3.v7.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/dayjs@1/locale/zh-tw.js"></script>
<script src="https://unpkg.com/cal-heatmap@4.0.0-beta.7/dist/cal-heatmap.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/cal-heatmap@4.0.0-beta.7/dist/cal-heatmap.css"></script>
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/cal-heatmap@4.0.0-beta.7/dist/plugins/Tooltip.min.js"></script>
<script src="https://unpkg.com/cal-heatmap@4.0.0-beta.7/dist/plugins/Legend.min.js"></script>
```

Javascript
```js
date: {
    timezone: 'Asia/Taipei',
    locale: 'zh-tw',
    start: '2023-01-01',
},
```

Painted dataset (I am set from 2023-01-01, but the dataset will start from 2022-12-01)
![image](https://user-images.githubusercontent.com/26423040/219255548-37fe6300-447e-4050-afe3-369aa066f112.png)
