### ISSUE TITLE
Date shifted by timezone

### ISSUE THREAD

**Issue by cpiekacz** [wa0x6e/cal-heatmap#307]
I have a data in csv format with dates in format YYYY-mm-dd, for example:
```
Date,Activities
2023-01-02,Gym
2023-01-03,Cycling
```
When I load the data, activities gets shifted by (minus) one day, so Gym get plotted on January 1st. I'm in the CET timezone so adding 2 hours fixes the problem, for example:
```
Date,Activities
2023-01-02 02:00,Gym
2023-01-03 02:00,Cycling
```

**Comment by wa0x6e** [comment]
Yes, I am aware of this issue, and is pending fix, see #306
