### ISSUE TITLE
How do I use schemes from d3 colors?

### ISSUE THREAD

**Issue by cpiekacz** [wa0x6e/cal-heatmap#309]
I would like to use [categorical](https://github.com/d3/d3-scale-chromatic#categorical) color schemes but can't figure out how to use them. Can anyone provide an example?

**Comment by wa0x6e** [comment]
The new documentation website has been pushed, take a look at https://cal-heatmap.com/docs/showcase 

Documentation for the color scheme will come soon.

**Comment by cpiekacz** [comment]
I did peek at the source on the previous documentation and these from what I can tell are the same. Use only use diverging color schemes (btw, what is the different between `type: 'diverging'` and `type: 'linear'`?). Would you be able provide an simple example of on how to define `scale` option for categorical scheme and so I could use 1, 2..n for values that would point to each of the colors?

**Comment by wa0x6e** [comment]
Examples will come soon, along updated documentation

diverging is using 3 colors, with the one in the middle acting as neutral, while linear is from color A to color B. Choice will depend on your data type. 

Temperature with minus values are better represented using diverging.

**Comment by cpiekacz** [comment]
Got it, thanks for explanation. It would be great if you could add this answer to the docs, I'm sure it will be helpful for other folks as well.

**Comment by wa0x6e** [comment]
A more detailed guide about scale type have been added:

https://cal-heatmap.com/docs/advanced/scaleType
