### ISSUE TITLE
Is there any method to remove dark mode 

### ISSUE THREAD

**Issue by ChiaYuSu** [wa0x6e/cal-heatmap#314]

**Comment by wa0x6e** [comment]
Can you explain the issue ?

**Comment by ChiaYuSu** [comment]
Because my site does not support dark mode
So if the heatmap color is too dark, it will make the site look bad
Therefore, I would like to ask if there is a way to turn off dark mode by default, thank you!

**Comment by wa0x6e** [comment]
I see, I will make it optional with an option

**Comment by ChiaYuSu** [comment]
Ok, thank you. Look forward to it.

**Comment by wa0x6e** [comment]
Added in beta9, see docs https://cal-heatmap.com/docs/options/theme
