### ISSUE TITLE
Issue with d3 7.6.1 

### ISSUE THREAD

**Issue by shojibur** [wa0x6e/cal-heatmap#320]
Thanks for awesome package, but seems it is unuseable due to following issue 

`reprise-balance-frontend-1  | ✘ [ERROR] No matching export in "node_modules/d3/src/index.js" for import "symbolTimes"
reprise-balance-frontend-1  | 
reprise-balance-frontend-1  |     node_modules/cal-heatmap/dist/cal-heatmap.esm.js:3:2085:
reprise-balance-frontend-1  |       3 │ ...symbolSquare2, symbolStar, symbolTimes, symbolTriangle, symbolTr...
reprise-balance-frontend-1  |         ╵                               ~~~~~~~~~~~
reprise-balance-frontend-1  | 
reprise-balance-frontend-1  | /srv/app/node_modules/esbuild/lib/main.js:1575
reprise-balance-frontend-1  |   let error = new Error(`${text}${summary}`);
reprise-balance-frontend-1  |               ^
reprise-balance-frontend-1  | 
reprise-balance-frontend-1  | Error: Build failed with 1 error:
reprise-balance-frontend-1  | node_modules/cal-heatmap/dist/cal-heatmap.esm.js:3:2085: ERROR: No matching export in "node_modules/d3/src/index.js" for import "symbolTimes"
reprise-balance-frontend-1  |     at failureErrorWithLog (/srv/app/node_modules/esbuild/lib/main.js:1575:15)
reprise-balance-frontend-1  |     at /srv/app/node_modules/esbuild/lib/main.js:1033:28
reprise-balance-frontend-1  |     at runOnEndCallbacks (/srv/app/node_modules/esbuild/lib/main.js:1447:61)
reprise-balance-frontend-1  |     at buildResponseToResult (/srv/app/node_modules/esbuild/lib/main.js:1031:7)
reprise-balance-frontend-1  |     at /srv/app/node_modules/esbuild/lib/main.js:1143:14
reprise-balance-frontend-1  |     at responseCallbacks.<computed> (/srv/app/node_modules/esbuild/lib/main.js:680:9)
reprise-balance-frontend-1  |     at handleIncomingPacket (/srv/app/node_modules/esbuild/lib/main.js:735:9)
reprise-balance-frontend-1  |     at Socket.readFromStdout (/srv/app/node_modules/esbuild/lib/main.js:656:7)
reprise-balance-frontend-1  |     at Socket.emit (node:events:527:28)
reprise-balance-frontend-1  |     at addChunk (node:internal/streams/readable:324:12) {
reprise-balance-frontend-1  |   errors: [
reprise-balance-frontend-1  |     {
reprise-balance-frontend-1  |       detail: undefined,
reprise-balance-frontend-1  |       id: '',
reprise-balance-frontend-1  |       location: {
reprise-balance-frontend-1  |         column: 2085,
reprise-balance-frontend-1  |         file: 'node_modules/cal-heatmap/dist/cal-heatmap.esm.js',
reprise-balance-frontend-1  |         length: 11,
reprise-balance-frontend-1  |         line: 3,
reprise-balance-frontend-1  |         lineText: "import { timeSecond, timeMinute, timeHour, timeDay, timeWeek, timeMonth, timeYear, timeMonday, timeTuesday, timeWednesday, timeThursday, timeFriday, timeSaturday, timeSunday, utcSecond, utcMinute, utcHour, utcDay, utcWeek, utcMonth, utcYear, utcMonday, utcTuesday, utcWednesday, utcThursday, utcFriday, utcSaturday, utcSunday, range, descending, color as color$1, ascending, schemeAccent, schemeCategory10, schemeDark2, schemePaired, schemePastel1, schemePastel2, schemeSet1, schemeSet2, schemeSet3, schemeTableau10, quantize, interpolateBrBG, interpolatePRGn, interpolatePiYG, interpolatePuOr, interpolateRdBu, interpolateRdGy, interpolateRdYlBu, interpolateRdYlGn, interpolateSpectral, interpolateBlues, interpolateGreens, interpolateGreys, interpolatePurples, interpolateReds, interpolateOranges, interpolateTurbo, interpolateViridis, interpolateMagma, interpolateInferno, interpolatePlasma, interpolateCividis, interpolateCubehelixDefault, interpolateWarm, interpolateCool, interpolateBuGn, interpolateBuPu, interpolateGnBu, interpolateOrRd, interpolatePuBuGn, interpolatePuBu, interpolatePuRd, interpolateRdPu, interpolateYlGnBu, interpolateYlGn, interpolateYlOrBr, interpolateYlOrRd, interpolateRainbow, interpolateSinebow, schemeBrBG, schemePRGn, schemePiYG, schemePuOr, schemeRdBu, schemeRdGy, schemeRdYlBu, schemeRdYlGn, schemeSpectral, schemeBlues, schemeGreens, schemeGreys, schemeOranges, schemePurples, schemeReds, schemeBuGn, schemeBuPu, schemeGnBu, schemeOrRd, schemePuBu, schemePuBuGn, schemePuRd, schemeRdPu, schemeYlGn, schemeYlGnBu, schemeYlOrBr, schemeYlOrRd, scaleLinear, scalePow, scaleLog, scaleSymlog, scaleQuantile, extent, ticks, interpolateNumber, pairs, reverse, scaleThreshold, scaleIdentity, max as max$4, interpolateRgb, interpolateRound, min as min$4, quantile, median, interpolateHsl, interpolateHcl, interpolateLab, scaleDiverging, scaleDivergingPow, scaleDivergingLog, scaleDivergingSymlog, piecewise, scaleTime, scaleUtc, symbolAsterisk, symbolCircle, symbolCross, symbolDiamond, symbolDiamond2, symbolPlus, symbolSquare, symbolSquare2, symbolStar, symbolTimes, symbolTriangle, symbolTriangle2, symbolWye, scaleImplicit, scaleOrdinal, scalePoint, scaleBand, InternSet, sort, symbolsStroke, symbolsFill } from 'd3';",
reprise-balance-frontend-1  |         namespace: '',
reprise-balance-frontend-1  |         suggestion: ''
reprise-balance-frontend-1  |       },
reprise-balance-frontend-1  |       notes: [],
reprise-balance-frontend-1  |       pluginName: '',
reprise-balance-frontend-1  |       text: 'No matching export in "node_modules/d3/src/index.js" for import "symbolTimes"'
reprise-balance-frontend-1  |     }
reprise-balance-frontend-1  |   ],
reprise-balance-frontend-1  |   warnings: []
reprise-balance-frontend-1  | }
reprise-balance-frontend-1  | 
reprise-balance-frontend-1  | Node.js v17.9.1`

**Comment by wa0x6e** [comment]
What is the d3.js version ?

How are you setting up the script ?

**Comment by shojibur** [comment]
Tried both way, same issue ( using it with vue 3 )

`import CalHeatmap from 'cal-heatmap';`
and also `import * as CalHeatmap from 'cal-heatmap';`

**Comment by shojibur** [comment]
WDYT ? Is it even useable with vue js ? wondering

**Comment by wa0x6e** [comment]
I will do some tests with vuejs.

**Comment by wa0x6e** [comment]
Just tried creating a new VueJS app with 

```
npm init vue@latest
```

Then followed all install instruction for a basic vue js app, then added the library via npm

```
npm add cal-heatmap@4.0.0-beta.11
```

then created a `src/components/CalHeatmap.vue`, with 

```
<script setup>
import { onMounted } from 'vue'
import CalHeatmap from 'cal-heatmap'

const cal = new CalHeatmap()

function paintCalendar() {
  cal.paint()
}

onMounted(() => paintCalendar())
</script>
```

and then used in App.vue, with 

```
<script>
import CalHeatmap from './components/CalHeatmap.vue'
</script>

<template>
<CalHeatmap />
</template>
```

No errors, everything worked fine

**Comment by shojibur** [comment]
Thanks for checking, 
Not sure i am still getting error with my existing project, but tried with new project it seems working.

**Comment by wa0x6e** [comment]
Closing since issue is not related to the library itself
