### ISSUE TITLE
Tooltip plugin, and others are not importable

### ISSUE THREAD

**Issue by spookylukey** [wa0x6e/cal-heatmap#326]
The [docs](https://cal-heatmap.com/docs/plugins/tooltip) say this for NPM:

> The plugin is built-in in the core CalHeatmap, just import the module with
>
> import { Tooltip } from 'cal-heatmap';

However, this doesn't appear to work. Typescript says `Module '"cal-heatmap"' has no exported member 'Tooltip'`, the package.json doesn't mention the plugins, and `cal-heatmap.esm.js` file doesn't mention them at all. 

Is this a package.json error?

Thanks

**Comment by wa0x6e** [comment]
`4.1.0` has been released with the fix.

Use

> import Tooltip from 'cal-heatmap/plugins/Tooltip';

**Comment by spookylukey** [comment]
Thanks again!
