### ISSUE TITLE
subdomain type using ghday start date & end date is not the same as locale

### ISSUE THREAD

**Issue by ChiaYuSu** [wa0x6e/cal-heatmap#328]
I don't know if it's because I didn't set locale: 'zh-tw' in date is not set to locale: 'zh-tw', so the problem is caused by
start date is not start at 2022/01/01, is start at 2022/01/02
<img width="817" alt="image" src="https://user-images.githubusercontent.com/26423040/222794076-ffd3ca45-eba3-4898-b19f-51f834d3b0ac.png">

But if I set loacle: 'zh-tw' console, the following problem occurs
<img width="575" alt="image" src="https://user-images.githubusercontent.com/26423040/222793863-9f905a9c-0c4f-459f-880a-facba97e0f7a.png">

**Comment by wa0x6e** [comment]
what is the used `subDomain` ?

**Comment by wa0x6e** [comment]
as explained in the docs, domain start and end is not guaranteed to be exactly the first and last day of the month 

https://cal-heatmap.com/docs/options/subDomain#ghday

it's snapped to the last and first week of the month, to avoid duplicate columns on navigation
