### ISSUE TITLE
TypeError: d.root is null

### ISSUE THREAD

**Issue by yaya3939** [wa0x6e/cal-heatmap#332]
Hello. I want to use it in my react component. But I got this error in console :
    **React Router caught the following error during render TypeError: d.root is null**
       **paint          cal-heatmap.min.js:8**
        **Anchor      Anchor.js:9**         //where i call cal.paint()

Error in page :
**d.root is null**
**./node_modules/cal-heatmap/cal-heatmap.min.js/CalHeatMap/this.paint@http://localhost:3000/static/js/bundle.js:22799:15**
**Anchor@http://localhost:3000/static/js/bundle.js:249:7**

I have searched issues, it seems no similar question, so I post this new issue.
Can u tell me why an how I can fix it?

**Comment by wa0x6e** [comment]
Can you share a code sample ? How are you importing and using ? Are you using webpacker ?

**Comment by yaya3939** [comment]
Thanx for ur quick answer.
I am using the webpack, the npx react default one.
my code : 
`import React from "react";
import PropTypes from "prop-types";
import CalHeatmap from "cal-heatmap";

const Anchor = ({ anchor: { title, color, from, to, records } }) => {
  const { date, rate, text } = records;

  const cal = new CalHeatmap();
  cal.paint({
    data: { source: records, x: "date", y: "rate" },
    range: 1,
    domain: { type: "month", padding: [10, 10, 10, 10] },
    subDomain: { type: "xDay", width: 15, height: 10, radius: 2, label: "D" },
    date: {
      highlight: [
        new Date("2020-01-15"),
        new Date(), // Highlight today
      ],
    },
    scale: {
      opacity: {
        baseColor: color,
        type: "linear",
        domain: [0, 5],
      },
    },
  });

  return (
    <div id="">
      <div id="cal-heatmap"></div>
    </div>
  );
};

export default Anchor;`

I'm testing, haven't modified code, so it's quite weird.

**Comment by wa0x6e** [comment]
is it also failing if you don't pass any options to paint() ?

**Comment by yaya3939** [comment]
I just try. It won't fail if no options and there are few cal-heatmap div in html of viewer.
But there's no image, just blank in page. 
Is it normal? It seems not same as the result shown in homepage.

**Comment by wa0x6e** [comment]
Are you using server side rendering ?

**Comment by yaya3939** [comment]
No, it's normal client side render react, but I do have a server to pass data.

**Comment by yaya3939** [comment]
Sorry, I just found it could work now....
Although don't know why, but it just works.
Thanx for your help!
