### ISSUE TITLE
how to set missing data value to 0

### ISSUE THREAD

**Issue by yaya3939** [wa0x6e/cal-heatmap#334]
Hello, my data doesn't include all date and value for everyday in the month. Missing data value is null, now. Because of it, My scale doesn't work like the way I hope. 
I set opacity , [0,5] domain in scale. I want all missing data subdomain's opacity to be 0.
But because missing data value is null, where I hope opacity 0 opacity is 1 now, just like value === 5.
I've tried using func(some conditional syntax) in x/y of data, but I found that it doesn't deal with missing data, it's about data already existed. 
And `considerMissingDataAsZero` seems not active now. 
Is there anyway to set missing data value 0?

**Comment by wa0x6e** [comment]
Will be added in next 4.2.0 release
