### ISSUE TITLE
Angular typescript crash

### ISSUE THREAD

**Issue by maykovieira** [wa0x6e/cal-heatmap#345]
I want to congratulate you for the component, it's been very useful in my project.

I'm currently having a problem, I'm developing an Angular Typescript project

I have the tsconfig.json file and when I add the parameter **noUnusedParameters = true** to the settings when running the build, the application gives an error:

**Error: node_modules/cal-heatmap/src/options/Options.ts:321:41 - error TS6133: 'objValue' is declared but its value is never read.
321 ...mergeWith(this.options, opts, (objValue, srcValue) => {
× Failed to compile.**

The problem is in the objValue variable that is not being used. To correct this in typescript there are some ways:
 
```
 this.options = {
       // eslint-disable-next-line arrow-body-style
       //@ts-ignore
       ...mergeWith(this.options, opts, (objValue, srcValue) => {
         return Array.isArray(srcValue) ? srcValue : undefined;
       }),
     };
```

or

```
  this.options = {
       // eslint-disable-next-line arrow-body-style
       ...mergeWith(this.options, opts, (_objValue, srcValue) => {
         return Array.isArray(srcValue) ? srcValue : undefined;
       }),
     };

```
That way it worked for my project.

The error happens at "node_modules\cal-heatmap\src\options\Options.ts"

Grateful

**Comment by wa0x6e** [comment]
Thanks, fixed in 4.2.3
