### ISSUE TITLE
Type is not correctly exported in "exports"

### ISSUE THREAD

**Issue by FallingEpiphany** [wa0x6e/cal-heatmap#452]
`  "types": "./src/index.d.ts" ` are not exported correctly in the package.json "exports" field. WIth VScode warn:

>   There are types at 'e:/Project_Rianprint/Rainprint-FrontEndApp/node_modules/@labzh/cal-heatmap/src/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@labzh/cal-heatmap' library may need to update its package.json or typings.ts(7016)

**Comment by wa0x6e** [comment]
Your error is coming from @labzh/cal-heatmap, which is a fork
