### ISSUE TITLE
Custom (sub) domains possible?

### ISSUE THREAD

**Issue by pvandenbrink** [wa0x6e/cal-heatmap#48]
Is it possible to create custom domains, for example by grouping subdomains together?

In our use case it would be ideal to have a month domain with two 'half-day' blocks as the subdomain, the first block representing hour 0-11 and the second block hour 12-23. It doesn't seem like cal-heatmap supports this currently, is it possible to add such functionality?

**Comment by cherrylipstick** [comment]
I also have a similar issue, I want 'day' as domain, but I don't want 'hour' as subdomain, I want the subdomain to be my own data, is it possible?
In the example attached I need family members to be the 'subdomain'...

![screen shot 2015-06-26 at 17 09 56](https://cloud.githubusercontent.com/assets/5595322/8386376/450be870-1c26-11e5-9870-eb8a5ba2e1c0.png)

**Comment by kamisama** [comment]
@cherrylipstick, no, it's impossible, as subdomain will always remain a time unit.

**Comment by nunoooo** [comment]
Hello, love heat map, but could it display 30 days from the present date, with only one square as subDomain, instead of 24h? 

So far i manage to do this:
![sem titulo](https://cloud.githubusercontent.com/assets/15262672/11366569/eb7deaa0-92a5-11e5-8dce-e582114e5443.png)

I've tried to edit further but with no success.

**Comment by wa0x6e** [comment]
You can't. Calendar always start at the start of the domain, e.g 1st of each month, day, etc ...

**Comment by nunoooo** [comment]
hum, ok, and if instead of day/hour, i use month/day, could i put a label for the day in the subDomain?

**Comment by wa0x6e** [comment]
what kind of label ?

**Comment by nunoooo** [comment]
so, a domain with the label of the month, and a label for the subDomain with the day

more or less this ex:
O       O     O      O     O        O
21    22    23    24     25      26
                  Nov

**Comment by wa0x6e** [comment]
yes, you can, but it'll display the whole month

**Comment by nunoooo** [comment]
Not a problem, could you point me out where to do that?

**Comment by wa0x6e** [comment]
Use the month domain, and days subdomain, then use colLimit: 1

http://wa0x6e.github.io/cal-heatmap/#colLimit

**Comment by nunoooo** [comment]
Awesome, i also found how to add the label inside, cheers mate very helpfull.

**Comment by paynecs** [comment]
Hi,

I'd like to have the momain set to one day, and the sub domain set to 30mins (one column per day, with 48 rows, each representing a 30 minute period).

Is this possible, please?

Thanks

**Comment by VigneshVaidyanathan** [comment]
@paynecs Did you find a solution for this? I also want to implement the same thing. Please let me know.
