### ISSUE TITLE
Displaying names of the days

### ISSUE THREAD

**Issue by dwiyatci** [wa0x6e/cal-heatmap#50]
Hi @kamisama,

is it possible to display names of the days of the week in month > day or month > x_day view, like the one in GitHub's contributions calendar?

![daynameslabel](https://f.cloud.github.com/assets/4405796/1366206/baa899a8-38bf-11e3-978c-4426dc789b71.png)

Thank you so much for your effort on this library.

Cheers!

**Comment by Misiu** [comment]
:+1:

**Comment by shakaw** [comment]
any news?

**Comment by kamisama** [comment]
Not yet

**Comment by PedroF20** [comment]
news?

**Comment by JoshKeegan** [comment]
:+1 Would be a great feature :)

Did anyone here implement anything just for there own heatmap?
I need to do this for days of the week & don't want to reinvent the wheel if someone else has already done this.

**Comment by hathawayj** [comment]
@wa0x6e how close to the top of the todo list is this item?

**Comment by wa0x6e** [comment]
Still working on it. It's not so easy, as label differs depending on the subDomain type. There's a long list of bugfixes waiting to be cleared before introducting new features. I think ETA is after summer 2017.

**Comment by hathawayj** [comment]
Thanks for the response.  Looking forward to updates.

**Comment by sataqi** [comment]
any update on this?

**Comment by wa0x6e** [comment]
Merged into v4

**Comment by dwiyatci** [comment]
@wa0x6e I really appreciate the efforts. I can still remember that I just turned 24 y.o. and was about to start my master thesis when I first requested this feature, and now I'm a 33 y.o. with a pretty stable job when the feature got merged. Feels like taking a good trip down memory lane this this issue〰 🏞🫡😌
