### ISSUE TITLE
Color for empty values

### ISSUE THREAD

**Issue by marcopovitch** [wa0x6e/cal-heatmap#59]
Hi, 

if I load my data with unset value (null) and if I set a lengendColors such as:
legendColors: { min: "red",
            max: "blue",
                empty: "grey" }

the cell with null value are not filled properly.

But it works if in addStyle function I add an extra check (d.v === 0 || d.v === null) 
such as:
if ((d.v === 0 || d.v === null) && options.legendColors !== null && options.legendColors.hasOwnProperty("empty"))

I hope I didn't misunderstood how lengendColors works.

Regards
Marc

**Comment by vlux** [comment]
@marcopovitch 
I encountered this bug today and use this code to set the rest rect to grey or whatever color u want.
`
$(".graph>svg>svg>g>rect:not(.r1,.r2,.r3,.r4,.r5)").css("fill","#ededed")
`
Hope it's useful for u

**Comment by andresDarriens** [comment]
If anyone is still interested on this, this was my solution.
css:
```
rect.r0 {
    fill: #ededed;
}
```
