### ISSUE TITLE
Is it possible to change the tooltip message ?

### ISSUE THREAD

**Issue by ghost** [wa0x6e/cal-heatmap#65]
When hovering over a cell containing a value, I get the following message:

[value] items on Monday, January [d], [YYY]

Is it possible to customize the message? For instance, I'd like instead to show:

[dd mmmm yy], value: [value]

**Comment by incorrectusername** [comment]
where did you find that in the docs?which section? i tried searching.

**Comment by wa0x6e** [comment]
http://cal-heatmap.com/#subDomainTitleFormat
