### ISSUE TITLE
Enhancement: Tooltip content

### ISSUE THREAD

**Issue by natebird** [wa0x6e/cal-heatmap#75]
Is it possible to change the content of the Tooltip?

I'm looking to have something like the following:

February 14, 2014
Metric A: value
Metric B: value
Metric C: value

**Comment by ravish1915** [comment]
@wa0x6e  Is it possible to make "10 min" as a subdomain instead of "min"? We have data that is updating every 10 min.

**Comment by wa0x6e** [comment]
No yet
