### ISSUE TITLE
Weird bug with one of the values not presented correctly

### ISSUE THREAD

**Issue by iglocska** [wa0x6e/cal-heatmap#76]
Not sure what is causing this, but all of the fields get shaded correctly except for one, which shows up as empty (however, hovering over it will show the correct value - it's just the colouring that is missing).

![cal-heatmap](https://f.cloud.github.com/assets/3668672/2085816/64255e62-8e4c-11e3-82e7-672b5e8e4cd6.png)

my settings look like this:

cal.init({
    range: 5, 
    domain:"month", 
    subDomain:"x_day",
    start: new Date(<?php echo $startDateCal; ?>),
    data: "<?php echo $url; ?>/logs/returnDates.json",
    highlight: "now",
    domainDynamicDimension: false,
    cellSize: 20,
    cellPadding: 1,
    domainGutter: 10,
    legend: <?php echo $range;?>,
    legendCellSize: 15,
    previousSelector: "#goLeft",
    nextSelector: "#goRight"
});

the json returned by returnDates is:

{
    "1375740000": 27,
    "1389049200": 8,
    "1389135600": 36,
    "1389222000": 19,
    "1389308400": 10,
    "1389567600": 117,
    "1389654000": 37,
    "1389740400": 31,
    "1389826800": 18,
    "1389913200": 11,
    "1390258800": 31,
    "1390345200": 4,
    "1390431600": 12,
    "1390518000": 27,
    "1390777200": 39,
    "1390863600": 68,
    "1390950000": 77,
    "1391036400": 69,
    "1391122800": 47,
    "1391295600": 23,
    "1391382000": 2,
    "1391468400": 22
}

The value of $range is: [0, 23, 46, 70, 93]

Not sure if it's a bug or if I did something wrong :)

**Comment by wa0x6e** [comment]
Closed since inactive

**Comment by iglocska** [comment]
Sorry, completely forgot about this. I've just re-tested it on our current version and it works as intended. My apologies!
