### ISSUE TITLE
Year > Weeks aligning issue

### ISSUE THREAD

**Issue by Jonovono** [wa0x6e/cal-heatmap#87]
So I am trying to show a line of all weeks for each year.

I am getting a strange behaviour (or atleast I think it is strange). 

I am executing the following code:

```
<div id="cal-heatmap"></div>
<script type="text/javascript">
var cal = new CalHeatMap();
cal.init({
    domain: 'year',
    subDomain: 'week',
    cellPadding: 1,
    domainGutter: 0,
    cellSize: 6,
    range: 80,
    domainLabelFormat: function(i, val) {return console.log(i, val)},
    // start: new Date('1990-03-11'),
    displayLegend: false,
    verticalOrientation: true,
    label: {
        position: "left",
        offset: {
            x: 20,
            y: 12
        },
    },
});
```

This is how it shows up: http://i.imgur.com/0n9s7wU.png

Shouldn't the blocks all be in the same line? Why do some stick out? And start at like January week #00.

Thanks!

**Comment by wa0x6e** [comment]
Fixed in v4
