### ISSUE TITLE
Add 'middle' value for legend

### ISSUE THREAD

**Issue by hetong007** [wa0x6e/cal-heatmap#91]
Hi, I am using your script to visualize the difference of the stock price. I want to use `'red'` to represent decreasing and `'green'` to represent increasing. But the HCL interpolation is ugly since the middle color is brown. 

Is it possible to define a `'middle'` color, so that I can use 'white' to guide the color interpolation and make the plot better? Thank you very much.

**Comment by wa0x6e** [comment]
Added in v4
