### ISSUE TITLE
D3JS version question

### ISSUE THREAD

**Issue by ssaptarshi** [wa0x6e/cal-heatmap#92]
Hi,

Can you please confirm if cal-heatmap is tested against the latest version of D3, i.e. 3.4.8
An update: just checked the package.json file, and it seems to indicate any D3 version equal to / higher than 3.0.6 is ok, so can one assume it to work with the latest version - i.e. has it been tested against the latest version ?

Thanks!

**Comment by kamisama** [comment]
Quick update: everything seems to works perfectly up to 3.5.6 (latest version as of 15/07/2015). 
The documentation website run on 3.5.6
