### ISSUE TITLE
When I jumpTo and highlight afterwards i sometime get some error

### ISSUE THREAD

**Issue by vladlep** [wa0x6e/cal-heatmap#96]
If i use jumpTo function to change the domain and the highlight function afterwards to highlight then new date

```
$MONTH_CALENDAR.jumpTo(newDate);
$MONTH_CALENDAR.highlight(newDate);
```

 i sometime get an error: 
Uncaught TypeError: Cannot read property 'length' of undefined;

```
Uncaught TypeError: Cannot read property 'length' of undefined d3.js:763
bind d3.js:763
d3_selectionPrototype.data d3.js:818
CalHeatMap.fill cal-heatmap.js:1354
CalHeatMap.highlight cal-heatmap.js:2825
setDayOnMonthCalendar hours_add.js:163
(anonymous function) hours_add.js:319
jQuery.event.dispatch jquery-1.10.0.js:5107
elemData.handle
```

The error shows in the d3 library because wrong data is passed, I presume, and group is undefined:

```
  function bind(group, groupData) {
       var i, n = group.length, 
```

**Comment by Yurko-Fedoriv** [comment]
I also got such issue, and I think it may be reproduced by triggering something like
```js
cal.update(data);
cal.options.data = data;
```

while previous domain change animation is still active. At least I was able to eliminate the issue by preventing the update during animation.

**Comment by Luiz-N** [comment]
@Yurko-Fedoriv is right... this error occurs if an update is attempted while an animation is still in progress. I fixed it by wrapping the update in a timeout equal to the `animationDuration` if a `jumpTo` was necessary

**Comment by wa0x6e** [comment]
Merged into v4
