### ISSUE TITLE
extend URL variables

### ISSUE THREAD

**Issue by ghost** [wa0x6e/cal-heatmap#98]
Are there any more variables like {{d:start}} and {{d:end}} ?
Would appreciate if there's also something like number of subdomains currently needed (e.g. {{d:numsubdomain}})?

**Comment by wa0x6e** [comment]
After some thinking, start/end date is the most suitable bounds.

step is useful only when domain navigation is by step, with adjacent domains, which is not always true.
The `jumpTo` function can load data far from the startDate, such as 25 domains aways, and in a calendar showing only 4 domains, the `startDate` will always be necessary, else you will load unnecessary data for the 21 domains you will not be using.
